// Generated by scripts/fetch_real_sources.mjs
const radarGeneratedArticles = [
  {
    "id": "real_nvidia_2026_08_17_securing_the_infrastructure_of_intelligence",
    "title": "Securing the Infrastructure of Intelligence",
    "signalCategory": "财报",
    "industry": "数据中心硬件",
    "topic": "",
    "companies": [
      "NVIDIA"
    ],
    "importance": "高",
    "sourceId": "nvidia_newsroom",
    "sourceUrl": "https://blogs.nvidia.com/blog/securing-the-infrastructure-of-intelligence/",
    "publishedAt": "2026-08-17",
    "summary": "This update on Securing the Infrastructure of Intelligence is relevant as an industry signal that should be reviewed for demand, supply, cost, technology or customer implications.",
    "whyItMatters": "10-K/10-Q 要重点抽取资本开支、库存、客户集中度、毛利和风险因素，不能只停留在 filing 本身。",
    "tags": [
      "AI",
      "HBM",
      "Networking",
      "Power",
      "NVIDIA"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 5,
    "sourceCategory": "official",
    "briefingValue": [
      "Supply signal"
    ],
    "impactScore": 27,
    "titleZh": "",
    "titleEn": "Securing the Infrastructure of Intelligence",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "高",
    "showByDefault": true
  },
  {
    "id": "real_nvidia_2026_08_17_nvidia_guarantees_sb_energy_s_ports_pike_technology_campus_in_ohio_to_exc",
    "title": "NVIDIA Guarantees SB Energy’s PORTS-Pike Technology Campus in Ohio to Exclusively Host NVIDIA AI Compute",
    "signalCategory": "公司动态",
    "industry": "3C 产品",
    "topic": "",
    "companies": [
      "NVIDIA"
    ],
    "importance": "高",
    "sourceId": "nvidia_newsroom",
    "sourceUrl": "https://nvidianews.nvidia.com/news/nvidia-guarantees-sb-energy-s-ports-pike-technology-campus-in-ohio-to-exclusively-host-nvidia-ai-compute",
    "publishedAt": "2026-08-17",
    "summary": "This update on NVIDIA Guarantees SB Energy’s PORTS-Pike Technology Campus in Ohio to Exclusively Host NVIDIA AI Compute is relevant as an industry signal that should be reviewed for demand, supply, cost, technology or customer implications.",
    "whyItMatters": "公司动态需要判断是否改变客户关系、技术路线或订单归属；没有落到这些变量上就不应放大解读。",
    "tags": [
      "AI",
      "Power",
      "NVIDIA"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 5,
    "sourceCategory": "official",
    "briefingValue": [
      "Supply signal",
      "Customer move"
    ],
    "impactScore": 39,
    "titleZh": "",
    "titleEn": "NVIDIA Guarantees SB Energy’s PORTS-Pike Technology Campus in Ohio to Exclusively Host NVIDIA AI Compute",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "中",
    "showByDefault": true
  },
  {
    "id": "real_nvidia_2026_08_14_universitas_gadjah_mada_indosat_and_nvidia_open_indonesia_s_first_univers",
    "title": "Universitas Gadjah Mada, Indosat and NVIDIA Open Indonesia’s First University AI Center to Develop Local AI Talent",
    "signalCategory": "产品",
    "industry": "3C 产品",
    "topic": "",
    "companies": [
      "NVIDIA"
    ],
    "importance": "低",
    "sourceId": "nvidia_newsroom",
    "sourceUrl": "https://blogs.nvidia.com/blog/ugm-indosat-nvidia-ai-technology-center/",
    "publishedAt": "2026-08-14",
    "summary": "This update on Universitas Gadjah Mada, Indosat and NVIDIA Open Indonesia’s First University AI Center to Develop Local AI Talent is relevant as an industry signal that should be reviewed for demand, supply, cost, technology or customer implications.",
    "whyItMatters": "产品信号只有在带来规格升级、备货变化或供应商切换时，才应进入管理层优先阅读。",
    "tags": [
      "AI",
      "Packaging",
      "NVIDIA"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 5,
    "sourceCategory": "official",
    "briefingValue": [
      "Customer move"
    ],
    "impactScore": 0,
    "titleZh": "",
    "titleEn": "Universitas Gadjah Mada, Indosat and NVIDIA Open Indonesia’s First University AI Center to Develop Local AI Talent",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false
  },
  {
    "id": "real_nvidia_2026_08_13_class_is_in_session_geforce_now_levels_up_linux_chromebooks_and_more",
    "title": "Class Is in Session: GeForce NOW Levels Up Linux, Chromebooks and More",
    "signalCategory": "产品",
    "industry": "数据中心硬件",
    "topic": "",
    "companies": [
      "NVIDIA"
    ],
    "importance": "低",
    "sourceId": "nvidia_newsroom",
    "sourceUrl": "https://blogs.nvidia.com/blog/geforce-now-thursday-linux-native-app/",
    "publishedAt": "2026-08-13",
    "summary": "The native Linux app for GeForce NOW is officially out of beta.",
    "whyItMatters": "立讯需要把重点放在整机柜、供电、散热、高速线缆和连接器，而不是只看 GPU 或服务器品牌。",
    "tags": [
      "Cloud",
      "Gaming",
      "NVIDIA"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 5,
    "sourceCategory": "official",
    "briefingValue": [],
    "impactScore": 0,
    "titleZh": "",
    "titleEn": "Class Is in Session: GeForce NOW Levels Up Linux, Chromebooks and More",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false
  },
  {
    "id": "real_nvidia_2026_08_12_nvidia_ceo_tops_glassdoor_s_2026_list_of_best_ceos",
    "title": "NVIDIA CEO Tops Glassdoor’s 2026 List of Best CEOs",
    "signalCategory": "产品",
    "industry": "3C 产品",
    "topic": "",
    "companies": [
      "NVIDIA"
    ],
    "importance": "高",
    "sourceId": "nvidia_newsroom",
    "sourceUrl": "https://blogs.nvidia.com/blog/nvidia-life-glassdoor-best-ceo-2026/",
    "publishedAt": "2026-08-12",
    "summary": "This memory update is relevant as a supply, pricing or architecture signal for server memory, HBM, NAND and downstream BOM planning.",
    "whyItMatters": "存储供给被 AI 数据中心吸走时，会同时影响服务器 BOM 和消费电子备货成本，需看缺货是否传导到客户排产。",
    "tags": [
      "AI",
      "Storage",
      "NVIDIA"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 5,
    "sourceCategory": "official",
    "briefingValue": [
      "Customer move"
    ],
    "impactScore": 22,
    "titleZh": "",
    "titleEn": "NVIDIA CEO Tops Glassdoor’s 2026 List of Best CEOs",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "高",
    "showByDefault": true
  },
  {
    "id": "real_nvidia_2026_08_12_nvidia_ai_factory_compute_is_becoming_an_investable_asset_class",
    "title": "NVIDIA AI Factory Compute Is Becoming an Investable Asset Class",
    "signalCategory": "公司动态",
    "industry": "数据中心硬件",
    "topic": "",
    "companies": [
      "NVIDIA"
    ],
    "importance": "高",
    "sourceId": "nvidia_newsroom",
    "sourceUrl": "https://blogs.nvidia.com/blog/nvidia-ai-factory-compute/",
    "publishedAt": "2026-08-12",
    "summary": "This update on NVIDIA AI Factory Compute Is Becoming an Investable Asset Class is relevant as an industry signal that should be reviewed for demand, supply, cost, technology or customer implications.",
    "whyItMatters": "这类信息关系到 AI 服务器从单卡采购转向整机柜交付，立讯应关注电源、散热、线束、连接器和组装复杂度变化。",
    "tags": [
      "AI",
      "NVIDIA"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 5,
    "sourceCategory": "official",
    "briefingValue": [
      "Customer move",
      "Capital allocation"
    ],
    "impactScore": 28,
    "titleZh": "",
    "titleEn": "NVIDIA AI Factory Compute Is Becoming an Investable Asset Class",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "中",
    "showByDefault": true
  },
  {
    "id": "real_nvidia_2026_08_11_why_scaling_ai_compute_performance_requires_a_new_power_architecture",
    "title": "Why Scaling AI Compute Performance Requires a New Power Architecture",
    "signalCategory": "供应链",
    "industry": "数据中心硬件",
    "topic": "",
    "companies": [
      "NVIDIA"
    ],
    "importance": "高",
    "sourceId": "nvidia_newsroom",
    "sourceUrl": "https://blogs.nvidia.com/blog/800-vdc-power-architecture-ai-factory/",
    "publishedAt": "2026-08-11",
    "summary": "This update on Why Scaling AI Compute Performance Requires a New Power Architecture is relevant as an industry signal that should be reviewed for demand, supply, cost, technology or customer implications.",
    "whyItMatters": "立讯需要把重点放在整机柜、供电、散热、高速线缆和连接器，而不是只看 GPU 或服务器品牌。",
    "tags": [
      "AI",
      "GPU",
      "Server",
      "Power",
      "NVIDIA"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 5,
    "sourceCategory": "official",
    "briefingValue": [
      "Demand signal",
      "Luxshare business fit"
    ],
    "impactScore": 33,
    "titleZh": "",
    "titleEn": "Why Scaling AI Compute Performance Requires a New Power Architecture",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "高",
    "showByDefault": true
  },
  {
    "id": "real_nvidia_2026_08_11_nvidia_and_local_ai_community_fuel_open_source_models_and_intelligent_age",
    "title": "NVIDIA and Local AI Community Fuel Open Source Models and Intelligent Agents",
    "signalCategory": "产品",
    "industry": "3C 产品",
    "topic": "",
    "companies": [
      "NVIDIA"
    ],
    "importance": "低",
    "sourceId": "nvidia_newsroom",
    "sourceUrl": "https://blogs.nvidia.com/blog/local-ai-open-source-models-agents-nemotron/",
    "publishedAt": "2026-08-11",
    "summary": "This product-platform update should be reviewed for sensor, optics, connector or final-assembly implications before raising its priority.",
    "whyItMatters": "对立讯的意义在于高速互连从服务器内部延伸到光链路，需观察光器件产能、客户认证和连接方案是否改变。",
    "tags": [
      "AI",
      "NVIDIA"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 5,
    "sourceCategory": "official",
    "briefingValue": [
      "Customer move"
    ],
    "impactScore": 0,
    "titleZh": "",
    "titleEn": "NVIDIA and Local AI Community Fuel Open Source Models and Intelligent Agents",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false
  },
  {
    "id": "real_nvidia_2026_08_11_nvidia_nemotron_3_5_lightning_and_nemo_switchyard_deliver_faster_smarter_",
    "title": "NVIDIA Nemotron 3.5 Lightning and NeMo Switchyard Deliver Faster, Smarter, More Efficient Agentic AI",
    "signalCategory": "产品",
    "industry": "3C 产品",
    "topic": "",
    "companies": [
      "NVIDIA"
    ],
    "importance": "高",
    "sourceId": "nvidia_newsroom",
    "sourceUrl": "https://blogs.nvidia.com/blog/nemotron-lightning-switchyard-rtx-dgx/",
    "publishedAt": "2026-08-11",
    "summary": "This update on NVIDIA Nemotron 3.5 Lightning and NeMo Switchyard Deliver Faster, Smarter, More Efficient Agentic AI is relevant as an industry signal that should be reviewed for demand, supply, cost, technology or customer implications.",
    "whyItMatters": "这类信息关系到 AI 服务器从单卡采购转向整机柜交付，立讯应关注电源、散热、线束、连接器和组装复杂度变化。",
    "tags": [
      "AI",
      "NVIDIA"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 5,
    "sourceCategory": "official",
    "briefingValue": [
      "Demand signal",
      "Customer move"
    ],
    "impactScore": 43,
    "titleZh": "",
    "titleEn": "NVIDIA Nemotron 3.5 Lightning and NeMo Switchyard Deliver Faster, Smarter, More Efficient Agentic AI",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "中",
    "showByDefault": false,
    "lowValueReason": "弱相关主题未命中明确业务落点"
  },
  {
    "id": "real_nvidia_2026_08_10_nvidia_partners_with_apollo_blackrock_blackstone_brookfield_goldman_sachs",
    "title": "NVIDIA Partners With Apollo, BlackRock, Blackstone, Brookfield, Goldman Sachs and KKR to Establish AI Compute Infrastructure Financing Platforms to Mobilize Over $500 Billion of Third-Party Capital",
    "signalCategory": "公司动态",
    "industry": "3C 产品",
    "topic": "",
    "companies": [
      "NVIDIA"
    ],
    "importance": "高",
    "sourceId": "nvidia_newsroom",
    "sourceUrl": "https://nvidianews.nvidia.com/news/nvidia-partners-with-apollo-blackrock-blackstone-brookfield-goldman-sachs-and-kkr-to-establish-ai-compute-infrastructure-financing-platforms-to-mobilize-over-500-billion-of-third-party-capital",
    "publishedAt": "2026-08-10",
    "summary": "This update on NVIDIA Partners With Apollo, BlackRock, Blackstone, Brookfield, Goldman Sachs and KKR to Establish AI Compute Infrastructure Financing Platforms to Mobilize Over $500 Billion of Third-Party Capital is relevant as an industry signal that should be reviewed for demand, supply, cost, technology or customer implications.",
    "whyItMatters": "公司动态需要判断是否改变客户关系、技术路线或订单归属；没有落到这些变量上就不应放大解读。",
    "tags": [
      "AI",
      "NVIDIA"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 5,
    "sourceCategory": "official",
    "briefingValue": [
      "Customer move",
      "Capital allocation"
    ],
    "impactScore": 28,
    "titleZh": "",
    "titleEn": "NVIDIA Partners With Apollo, BlackRock, Blackstone, Brookfield, Goldman Sachs and KKR to Establish AI Compute Infrastructure Financing Platforms to Mobilize Over $500 Billion of Third-Party Capital",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "中",
    "showByDefault": true
  },
  {
    "id": "real_nvidia_2026_08_08_firebird_launches_cis_region_s_largest_ai_factory_in_armenia",
    "title": "Firebird Launches CIS Region’s Largest AI Factory in Armenia",
    "signalCategory": "供应链",
    "industry": "数据中心硬件",
    "topic": "",
    "companies": [
      "NVIDIA"
    ],
    "importance": "高",
    "sourceId": "nvidia_newsroom",
    "sourceUrl": "https://blogs.nvidia.com/blog/firebird-ai-factory-armenia-blackwell-rubin-dsx/",
    "publishedAt": "2026-08-08",
    "summary": "This update on Firebird Launches CIS Region’s Largest AI Factory in Armenia is relevant as an industry signal that should be reviewed for demand, supply, cost, technology or customer implications.",
    "whyItMatters": "这类信息关系到 AI 服务器从单卡采购转向整机柜交付，立讯应关注电源、散热、线束、连接器和组装复杂度变化。",
    "tags": [
      "AI",
      "Cloud",
      "Power",
      "NVIDIA"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 5,
    "sourceCategory": "official",
    "briefingValue": [
      "Customer move"
    ],
    "impactScore": 22,
    "titleZh": "",
    "titleEn": "Firebird Launches CIS Region’s Largest AI Factory in Armenia",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "中",
    "showByDefault": true
  },
  {
    "id": "real_nvidia_2026_08_06_geforce_now_shakes_up_august_with_26_new_games",
    "title": "GeForce NOW Shakes Up August With 26 New Games",
    "signalCategory": "产品",
    "industry": "3C 产品",
    "topic": "",
    "companies": [
      "NVIDIA"
    ],
    "importance": "低",
    "sourceId": "nvidia_newsroom",
    "sourceUrl": "https://blogs.nvidia.com/blog/geforce-now-thursday-august-2026-games-list/",
    "publishedAt": "2026-08-06",
    "summary": "This update on GeForce NOW Shakes Up August With 26 New Games is relevant as an industry signal that should be reviewed for demand, supply, cost, technology or customer implications.",
    "whyItMatters": "产品信号只有在带来规格升级、备货变化或供应商切换时，才应进入管理层优先阅读。",
    "tags": [
      "Gaming",
      "NVIDIA"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 5,
    "sourceCategory": "official",
    "briefingValue": [],
    "impactScore": 0,
    "titleZh": "",
    "titleEn": "GeForce NOW Shakes Up August With 26 New Games",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false,
    "lowValueReason": "命中默认 feed 禁入弱信号且缺少强产业信号"
  },
  {
    "id": "real_sec_amd_8_k_2026_08_19_0000002488_26_000163",
    "title": "AMD filed 8-K",
    "signalCategory": "财报",
    "industry": "核心零部件",
    "topic": "8-K",
    "companies": [
      "AMD"
    ],
    "importance": "高",
    "sourceId": "sec_edgar",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/2488/000000248826000163/amd-20260817.htm",
    "publishedAt": "2026-08-19",
    "summary": "AMD 8-K filing is kept as a regulatory alert only; no concrete business disclosure was extracted from the source.",
    "whyItMatters": "8-K 只有在涉及客户、产能、融资、并购或重大合作时才值得升权；否则只作为背景信息保留。",
    "tags": [
      "Filings",
      "AMD"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 5,
    "sourceCategory": "regulatory",
    "briefingValue": [
      "Customer move"
    ],
    "impactScore": 10,
    "titleZh": "",
    "titleEn": "AMD filed 8-K",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "中",
    "showByDefault": false,
    "lowValueReason": "SEC 原始 filing 未抽到具体业务硬信号"
  },
  {
    "id": "real_sec_nvda_8_k_2026_08_17_0001045810_26_000069",
    "title": "NVIDIA filed 8-K",
    "signalCategory": "财报",
    "industry": "数据中心硬件",
    "topic": "8-K",
    "companies": [
      "NVIDIA"
    ],
    "importance": "中",
    "sourceId": "sec_edgar",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/1045810/000104581026000069/nvda-20260817.htm",
    "publishedAt": "2026-08-17",
    "summary": "NVIDIA 8-K filing is kept as a regulatory alert only; no concrete business disclosure was extracted from the source.",
    "whyItMatters": "8-K 只有在涉及客户、产能、融资、并购或重大合作时才值得升权；否则只作为背景信息保留。",
    "tags": [
      "Filings",
      "NVIDIA"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 5,
    "sourceCategory": "regulatory",
    "briefingValue": [
      "Customer move"
    ],
    "impactScore": 8,
    "titleZh": "",
    "titleEn": "NVIDIA filed 8-K",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "中",
    "showByDefault": false,
    "lowValueReason": "SEC 原始 filing 未抽到具体业务硬信号"
  },
  {
    "id": "real_sec_intc_8_k_2026_08_12_0001193125_26_346806",
    "title": "Intel filed 8-K",
    "signalCategory": "财报",
    "industry": "核心零部件",
    "topic": "8-K",
    "companies": [
      "Intel"
    ],
    "importance": "低",
    "sourceId": "sec_edgar",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/50863/000119312526346806/d117670d8k.htm",
    "publishedAt": "2026-08-12",
    "summary": "Intel 8-K filing is kept as a regulatory alert only; no concrete business disclosure was extracted from the source.",
    "whyItMatters": "8-K 只有在涉及客户、产能、融资、并购或重大合作时才值得升权；否则只作为背景信息保留。",
    "tags": [
      "Filings",
      "Intel"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 5,
    "sourceCategory": "regulatory",
    "briefingValue": [],
    "impactScore": 3,
    "titleZh": "",
    "titleEn": "Intel filed 8-K",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false,
    "lowValueReason": "SEC 原始 filing 未抽到具体业务硬信号"
  },
  {
    "id": "real_sec_googl_8_k_2026_08_10_0001193125_26_342390",
    "title": "Google filed 8-K",
    "signalCategory": "财报",
    "industry": "数据中心硬件",
    "topic": "8-K",
    "companies": [
      "Google"
    ],
    "importance": "低",
    "sourceId": "sec_edgar",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/1652044/000119312526342390/d171253d8k.htm",
    "publishedAt": "2026-08-10",
    "summary": "This update on Google filed 8-K requires source review before drawing conclusions about supply-chain exposure, financial risk or customer demand.",
    "whyItMatters": "8-K 只有在涉及客户、产能、融资、并购或重大合作时才值得升权；否则只作为背景信息保留。",
    "tags": [
      "Filings",
      "Google"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 5,
    "sourceCategory": "regulatory",
    "briefingValue": [
      "Customer move"
    ],
    "impactScore": 3,
    "titleZh": "",
    "titleEn": "Google filed 8-K",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false,
    "lowValueReason": "SEC 原始 filing 未抽到具体业务硬信号"
  },
  {
    "id": "real_sec_hpe_8_k_2026_08_04_0001645590_26_000074",
    "title": "HPE filed 8-K",
    "signalCategory": "财报",
    "industry": "数据中心硬件",
    "topic": "8-K",
    "companies": [
      "HPE"
    ],
    "importance": "低",
    "sourceId": "sec_edgar",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/1645590/000164559026000074/hpe-20260804.htm",
    "publishedAt": "2026-08-04",
    "summary": "This update on HPE filed 8-K requires source review before drawing conclusions about supply-chain exposure, financial risk or customer demand.",
    "whyItMatters": "这类信息关系到 AI 服务器从单卡采购转向整机柜交付，立讯应关注电源、散热、线束、连接器和组装复杂度变化。",
    "tags": [
      "Filings",
      "HPE"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 5,
    "sourceCategory": "regulatory",
    "briefingValue": [
      "Customer move"
    ],
    "impactScore": 3,
    "titleZh": "",
    "titleEn": "HPE filed 8-K",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false,
    "lowValueReason": "SEC 原始 filing 未抽到具体业务硬信号"
  },
  {
    "id": "real_sec_aapl_10_q_2026_07_31_0000320193_26_000020",
    "title": "Apple filed 10-Q",
    "signalCategory": "财报",
    "industry": "3C 产品",
    "topic": "10-Q",
    "companies": [
      "Apple"
    ],
    "importance": "低",
    "sourceId": "sec_edgar",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/320193/000032019326000020/aapl-20260627.htm",
    "publishedAt": "2026-07-31",
    "summary": "Apple 10-Q filing is kept as a regulatory alert only; no concrete business disclosure was extracted from the source.",
    "whyItMatters": "苹果链信号优先看两点：端侧硬件规格是否升级，以及云端 AI 投入是否带来新的服务器和互连需求。",
    "tags": [
      "Filings",
      "Apple"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 5,
    "sourceCategory": "regulatory",
    "briefingValue": [
      "Customer move"
    ],
    "impactScore": 3,
    "titleZh": "",
    "titleEn": "Apple filed 10-Q",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false,
    "lowValueReason": "SEC 原始 filing 未抽到具体业务硬信号"
  },
  {
    "id": "real_sec_qcom_8_k_2026_07_31_0001104659_26_089234",
    "title": "Qualcomm filed 8-K",
    "signalCategory": "财报",
    "industry": "核心零部件",
    "topic": "8-K",
    "companies": [
      "Qualcomm"
    ],
    "importance": "低",
    "sourceId": "sec_edgar",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/804328/000110465926089234/tm2621612d2_8k.htm",
    "publishedAt": "2026-07-31",
    "summary": "This update on Qualcomm filed 8-K requires source review before drawing conclusions about supply-chain exposure, financial risk or customer demand.",
    "whyItMatters": "8-K 只有在涉及客户、产能、融资、并购或重大合作时才值得升权；否则只作为背景信息保留。",
    "tags": [
      "Filings",
      "Qualcomm"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 5,
    "sourceCategory": "regulatory",
    "briefingValue": [
      "Customer move"
    ],
    "impactScore": 3,
    "titleZh": "",
    "titleEn": "Qualcomm filed 8-K",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false,
    "lowValueReason": "SEC 原始 filing 未抽到具体业务硬信号"
  },
  {
    "id": "real_sec_amzn_10_q_2026_07_31_0001018724_26_000026",
    "title": "Amazon filed 10-Q",
    "signalCategory": "财报",
    "industry": "数据中心硬件",
    "topic": "10-Q",
    "companies": [
      "Amazon"
    ],
    "importance": "低",
    "sourceId": "sec_edgar",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/1018724/000101872426000026/amzn-20260630.htm",
    "publishedAt": "2026-07-31",
    "summary": "This update on Amazon filed 10-Q requires source review before drawing conclusions about supply-chain exposure, financial risk or customer demand.",
    "whyItMatters": "10-K/10-Q 要重点抽取资本开支、库存、客户集中度、毛利和风险因素，不能只停留在 filing 本身。",
    "tags": [
      "Filings",
      "Amazon"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 5,
    "sourceCategory": "regulatory",
    "briefingValue": [
      "Customer move"
    ],
    "impactScore": 3,
    "titleZh": "",
    "titleEn": "Amazon filed 10-Q",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false,
    "lowValueReason": "SEC 原始 filing 未抽到具体业务硬信号"
  },
  {
    "id": "real_sec_aapl_8_k_2026_07_30_0000320193_26_000018",
    "title": "Apple filed 8-K",
    "signalCategory": "财报",
    "industry": "3C 产品",
    "topic": "8-K",
    "companies": [
      "Apple"
    ],
    "importance": "低",
    "sourceId": "sec_edgar",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/320193/000032019326000018/aapl-20260730.htm",
    "publishedAt": "2026-07-30",
    "summary": "Apple 8-K filing is kept as a regulatory alert only; no concrete business disclosure was extracted from the source.",
    "whyItMatters": "苹果链信号优先看两点：端侧硬件规格是否升级，以及云端 AI 投入是否带来新的服务器和互连需求。",
    "tags": [
      "Filings",
      "Apple"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 5,
    "sourceCategory": "regulatory",
    "briefingValue": [
      "Customer move"
    ],
    "impactScore": 3,
    "titleZh": "",
    "titleEn": "Apple filed 8-K",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false,
    "lowValueReason": "SEC 原始 filing 未抽到具体业务硬信号"
  },
  {
    "id": "real_sec_amzn_8_k_2026_07_30_0001018724_26_000024",
    "title": "Amazon filed 8-K",
    "signalCategory": "财报",
    "industry": "数据中心硬件",
    "topic": "8-K",
    "companies": [
      "Amazon"
    ],
    "importance": "低",
    "sourceId": "sec_edgar",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/1018724/000101872426000024/amzn-20260730.htm",
    "publishedAt": "2026-07-30",
    "summary": "This update on Amazon filed 8-K requires source review before drawing conclusions about supply-chain exposure, financial risk or customer demand.",
    "whyItMatters": "8-K 只有在涉及客户、产能、融资、并购或重大合作时才值得升权；否则只作为背景信息保留。",
    "tags": [
      "Filings",
      "Amazon"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 5,
    "sourceCategory": "regulatory",
    "briefingValue": [
      "Customer move"
    ],
    "impactScore": 3,
    "titleZh": "",
    "titleEn": "Amazon filed 8-K",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false,
    "lowValueReason": "SEC 原始 filing 未抽到具体业务硬信号"
  },
  {
    "id": "real_sec_msft_10_k_2026_07_29_0001193125_26_323660",
    "title": "Microsoft filed 10-K",
    "signalCategory": "财报",
    "industry": "数据中心硬件",
    "topic": "10-K",
    "companies": [
      "Microsoft"
    ],
    "importance": "低",
    "sourceId": "sec_edgar",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/789019/000119312526323660/msft-20260630.htm",
    "publishedAt": "2026-07-29",
    "summary": "Microsoft 10-K filing is kept as a regulatory alert only; no concrete business disclosure was extracted from the source.",
    "whyItMatters": "10-K/10-Q 要重点抽取资本开支、库存、客户集中度、毛利和风险因素，不能只停留在 filing 本身。",
    "tags": [
      "Filings",
      "Microsoft"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 5,
    "sourceCategory": "regulatory",
    "briefingValue": [
      "Customer move"
    ],
    "impactScore": 3,
    "titleZh": "",
    "titleEn": "Microsoft filed 10-K",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false,
    "lowValueReason": "SEC 原始 filing 未抽到具体业务硬信号"
  },
  {
    "id": "real_sec_msft_8_k_2026_07_29_0001193125_26_323632",
    "title": "Microsoft filed 8-K",
    "signalCategory": "财报",
    "industry": "数据中心硬件",
    "topic": "8-K",
    "companies": [
      "Microsoft"
    ],
    "importance": "低",
    "sourceId": "sec_edgar",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/789019/000119312526323632/msft-20260729.htm",
    "publishedAt": "2026-07-29",
    "summary": "Microsoft 8-K filing is kept as a regulatory alert only; no concrete business disclosure was extracted from the source.",
    "whyItMatters": "8-K 只有在涉及客户、产能、融资、并购或重大合作时才值得升权；否则只作为背景信息保留。",
    "tags": [
      "Filings",
      "Microsoft"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 5,
    "sourceCategory": "regulatory",
    "briefingValue": [
      "Customer move"
    ],
    "impactScore": 3,
    "titleZh": "",
    "titleEn": "Microsoft filed 8-K",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false,
    "lowValueReason": "SEC 原始 filing 未抽到具体业务硬信号"
  },
  {
    "id": "real_sec_qcom_10_q_2026_07_29_0000804328_26_000086",
    "title": "Qualcomm filed 10-Q",
    "signalCategory": "财报",
    "industry": "核心零部件",
    "topic": "10-Q",
    "companies": [
      "Qualcomm"
    ],
    "importance": "低",
    "sourceId": "sec_edgar",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/804328/000080432826000086/qcom-20260628.htm",
    "publishedAt": "2026-07-29",
    "summary": "This update on Qualcomm filed 10-Q requires source review before drawing conclusions about supply-chain exposure, financial risk or customer demand.",
    "whyItMatters": "10-K/10-Q 要重点抽取资本开支、库存、客户集中度、毛利和风险因素，不能只停留在 filing 本身。",
    "tags": [
      "Filings",
      "Qualcomm"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 5,
    "sourceCategory": "regulatory",
    "briefingValue": [
      "Customer move"
    ],
    "impactScore": 3,
    "titleZh": "",
    "titleEn": "Qualcomm filed 10-Q",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false,
    "lowValueReason": "SEC 原始 filing 未抽到具体业务硬信号"
  },
  {
    "id": "real_sec_intc_10_q_2026_07_24_0000050863_26_000157",
    "title": "Intel filed 10-Q",
    "signalCategory": "财报",
    "industry": "核心零部件",
    "topic": "10-Q",
    "companies": [
      "Intel"
    ],
    "importance": "低",
    "sourceId": "sec_edgar",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/50863/000005086326000157/intc-20260627.htm",
    "publishedAt": "2026-07-24",
    "summary": "Intel 10-Q filing is kept as a regulatory alert only; no concrete business disclosure was extracted from the source.",
    "whyItMatters": "10-K/10-Q 要重点抽取资本开支、库存、客户集中度、毛利和风险因素，不能只停留在 filing 本身。",
    "tags": [
      "Filings",
      "Intel"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 5,
    "sourceCategory": "regulatory",
    "briefingValue": [],
    "impactScore": 3,
    "titleZh": "",
    "titleEn": "Intel filed 10-Q",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false,
    "lowValueReason": "SEC 原始 filing 未抽到具体业务硬信号"
  },
  {
    "id": "real_sec_mu_10_q_2026_06_25_0000723125_26_000015",
    "title": "Micron filed 10-Q",
    "signalCategory": "财报",
    "industry": "核心零部件",
    "topic": "10-Q",
    "companies": [
      "Micron"
    ],
    "importance": "低",
    "sourceId": "sec_edgar",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/723125/000072312526000015/mu-20260528.htm",
    "publishedAt": "2026-06-25",
    "summary": "This update on Micron filed 10-Q requires source review before drawing conclusions about supply-chain exposure, financial risk or customer demand.",
    "whyItMatters": "10-K/10-Q 要重点抽取资本开支、库存、客户集中度、毛利和风险因素，不能只停留在 filing 本身。",
    "tags": [
      "Filings",
      "Micron"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 5,
    "sourceCategory": "regulatory",
    "briefingValue": [],
    "impactScore": 3,
    "titleZh": "",
    "titleEn": "Micron filed 10-Q",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false,
    "lowValueReason": "SEC 原始 filing 未抽到具体业务硬信号"
  },
  {
    "id": "real_sec_mu_8_k_2026_06_24_0000723125_26_000013",
    "title": "Micron filed 8-K",
    "signalCategory": "财报",
    "industry": "核心零部件",
    "topic": "8-K",
    "companies": [
      "Micron"
    ],
    "importance": "低",
    "sourceId": "sec_edgar",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/723125/000072312526000013/mu-20260624.htm",
    "publishedAt": "2026-06-24",
    "summary": "This update on Micron filed 8-K requires source review before drawing conclusions about supply-chain exposure, financial risk or customer demand.",
    "whyItMatters": "8-K 只有在涉及客户、产能、融资、并购或重大合作时才值得升权；否则只作为背景信息保留。",
    "tags": [
      "Filings",
      "Micron"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 5,
    "sourceCategory": "regulatory",
    "briefingValue": [],
    "impactScore": 3,
    "titleZh": "",
    "titleEn": "Micron filed 8-K",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false,
    "lowValueReason": "SEC 原始 filing 未抽到具体业务硬信号"
  },
  {
    "id": "real_sec_hpe_10_q_2026_06_02_0001645590_26_000055",
    "title": "HPE filed 10-Q",
    "signalCategory": "财报",
    "industry": "数据中心硬件",
    "topic": "10-Q",
    "companies": [
      "HPE"
    ],
    "importance": "低",
    "sourceId": "sec_edgar",
    "sourceUrl": "https://www.sec.gov/Archives/edgar/data/1645590/000164559026000055/hpe-20260430.htm",
    "publishedAt": "2026-06-02",
    "summary": "This update on HPE filed 10-Q requires source review before drawing conclusions about supply-chain exposure, financial risk or customer demand.",
    "whyItMatters": "这类信息关系到 AI 服务器从单卡采购转向整机柜交付，立讯应关注电源、散热、线束、连接器和组装复杂度变化。",
    "tags": [
      "Filings",
      "HPE"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 5,
    "sourceCategory": "regulatory",
    "briefingValue": [
      "Customer move"
    ],
    "impactScore": 3,
    "titleZh": "",
    "titleEn": "HPE filed 10-Q",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false,
    "lowValueReason": "SEC 原始 filing 未抽到具体业务硬信号"
  },
  {
    "id": "real_eetimes_2026_08_19_running_local_llms_on_the_arduino_uno_q_board_a_practical_guide",
    "title": "Running Local LLMs on the Arduino® UNO™ Q Board: a Practical Guide",
    "signalCategory": "供应链",
    "industry": "核心零部件",
    "topic": "",
    "companies": [
      "EE Times"
    ],
    "importance": "低",
    "sourceId": "eetimes",
    "sourceUrl": "https://www.eetimes.com/running-local-llms-on-the-arduino-uno-q-board-a-practical-guide/",
    "publishedAt": "2026-08-19",
    "summary": "This update on Running Local LLMs on the Arduino® UNO™ Q Board: a Practical Guide is relevant as an industry signal that should be reviewed for demand, supply, cost, technology or customer implications.",
    "whyItMatters": "核心零部件信号要落到供给瓶颈、BOM 成本、客户认证和量产节奏上，否则容易变成技术噪音。",
    "tags": [
      "AI",
      "HBM",
      "EE Times"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 3,
    "sourceCategory": "discovery",
    "briefingValue": [],
    "impactScore": 0,
    "titleZh": "",
    "titleEn": "Running Local LLMs on the Arduino® UNO™ Q Board: a Practical Guide",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false
  },
  {
    "id": "real_eetimes_2026_08_18_marvell_targets_ai_bottlenecks_with_memory_disaggregation_portfolio",
    "title": "Marvell Targets AI Bottlenecks with Memory-Disaggregation Portfolio",
    "signalCategory": "供应链",
    "industry": "核心零部件",
    "topic": "",
    "companies": [
      "Marvell"
    ],
    "importance": "高",
    "sourceId": "eetimes",
    "sourceUrl": "https://www.eetimes.com/marvell-targets-ai-bottlenecks-with-memory-disaggregation-portfolio/",
    "publishedAt": "2026-08-18",
    "summary": "This update on Marvell Targets AI Bottlenecks with Memory-Disaggregation Portfolio signals memory-supply pressure or architecture change that can affect AI servers, data-center hardware and BOM planning.",
    "whyItMatters": "存储供给被 AI 数据中心吸走时，会同时影响服务器 BOM 和消费电子备货成本，需看缺货是否传导到客户排产。",
    "tags": [
      "AI",
      "HBM",
      "Storage",
      "Marvell"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 3,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Supply signal",
      "Risk event"
    ],
    "impactScore": 31,
    "titleZh": "",
    "titleEn": "Marvell Targets AI Bottlenecks with Memory-Disaggregation Portfolio",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "高",
    "showByDefault": true
  },
  {
    "id": "real_eetimes_2026_08_18_why_standardized_interfaces_are_critical_to_accelerating_humanoid_develo",
    "title": "Why Standardized Interfaces Are Critical to Accelerating Humanoid Development",
    "signalCategory": "供应链",
    "industry": "3C 产品",
    "topic": "",
    "companies": [
      "EE Times"
    ],
    "importance": "低",
    "sourceId": "eetimes",
    "sourceUrl": "https://www.eetimes.com/why-standardized-interfaces-are-critical-to-accelerating-humanoid-development/",
    "publishedAt": "2026-08-18",
    "summary": "This update on Why Standardized Interfaces Are Critical to Accelerating Humanoid Development is relevant as an industry signal that should be reviewed for demand, supply, cost, technology or customer implications.",
    "whyItMatters": "产品信号只有在带来规格升级、备货变化或供应商切换时，才应进入管理层优先阅读。",
    "tags": [
      "AI",
      "Power",
      "EE Times"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 3,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Cost signal"
    ],
    "impactScore": 0,
    "titleZh": "",
    "titleEn": "Why Standardized Interfaces Are Critical to Accelerating Humanoid Development",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false
  },
  {
    "id": "real_eetimes_2026_08_17_automotive_functional_safety_why_asil_compliance_starts_with_electromagn",
    "title": "Automotive Functional Safety: Why ASIL Compliance Starts with Electromagnetic Design",
    "signalCategory": "供应链",
    "industry": "3C 产品",
    "topic": "",
    "companies": [
      "EE Times"
    ],
    "importance": "中",
    "sourceId": "eetimes",
    "sourceUrl": "https://www.eetimes.com/automotive-functional-safety-why-asil-compliance-starts-with-electromagnetic-design/",
    "publishedAt": "2026-08-17",
    "summary": "This update on Automotive Functional Safety: Why ASIL Compliance Starts with Electromagnetic Design is relevant as an industry signal that should be reviewed for demand, supply, cost, technology or customer implications.",
    "whyItMatters": "产品信号只有在带来规格升级、备货变化或供应商切换时，才应进入管理层优先阅读。",
    "tags": [
      "AI",
      "Networking",
      "Automotive",
      "Power",
      "EE Times"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 3,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Competitor move",
      "Luxshare business fit"
    ],
    "impactScore": 9,
    "titleZh": "",
    "titleEn": "Automotive Functional Safety: Why ASIL Compliance Starts with Electromagnetic Design",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "中",
    "showByDefault": true
  },
  {
    "id": "real_semiconductor_engineering_2026_08_19_the_future_of_ai_compute_won_t_run_on_just_one_kind_of",
    "title": "The Future Of AI Compute Won’t Run On Just One Kind Of Chip",
    "signalCategory": "供应链",
    "industry": "数据中心硬件",
    "topic": "",
    "companies": [
      "Semiconductor Engineering"
    ],
    "importance": "中",
    "sourceId": "semiconductor_engineering",
    "sourceUrl": "https://semiengineering.com/the-future-of-ai-compute-wont-run-on-just-one-kind-of-chip/",
    "publishedAt": "2026-08-19",
    "summary": "This update on The Future Of AI Compute Won’t Run On Just One Kind Of Chip is relevant as an industry signal that should be reviewed for demand, supply, cost, technology or customer implications.",
    "whyItMatters": "立讯需要把重点放在整机柜、供电、散热、高速线缆和连接器，而不是只看 GPU 或服务器品牌。",
    "tags": [
      "AI",
      "GPU",
      "Data Center",
      "Power",
      "Semiconductor Engineering"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 3,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Cost signal",
      "Technology shift"
    ],
    "impactScore": 9,
    "titleZh": "",
    "titleEn": "The Future Of AI Compute Won’t Run On Just One Kind Of Chip",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "中",
    "showByDefault": true
  },
  {
    "id": "real_semiconductor_engineering_2026_08_19_blog_review_aug_19",
    "title": "Blog Review: Aug. 19",
    "signalCategory": "供应链",
    "industry": "核心零部件",
    "topic": "",
    "companies": [
      "Semiconductor Engineering"
    ],
    "importance": "低",
    "sourceId": "semiconductor_engineering",
    "sourceUrl": "https://semiengineering.com/blog-review-aug-19-3/",
    "publishedAt": "2026-08-19",
    "summary": "19 Memory tagging; digital twin of the Moon; packaging moves front-and-center; streaming sensor data.",
    "whyItMatters": "存储供给被 AI 数据中心吸走时，会同时影响服务器 BOM 和消费电子备货成本，需看缺货是否传导到客户排产。",
    "tags": [
      "HBM",
      "Semiconductor Engineering"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 3,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Supply signal"
    ],
    "impactScore": 0,
    "titleZh": "",
    "titleEn": "Blog Review: Aug. 19",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false
  },
  {
    "id": "real_semiconductor_engineering_2026_08_18_semiconductor_earnings_roundup_revenue_growth_and_take",
    "title": "Semiconductor Earnings Roundup: Revenue, Growth and Takeaways",
    "signalCategory": "财报",
    "industry": "核心零部件",
    "topic": "",
    "companies": [
      "Semiconductor Engineering"
    ],
    "importance": "中",
    "sourceId": "semiconductor_engineering",
    "sourceUrl": "https://semiengineering.com/chip-industry-earnings-roundup/",
    "publishedAt": "2026-08-18",
    "summary": "This update on Semiconductor Earnings Roundup: Revenue, Growth and Takeaways is relevant as an industry signal that should be reviewed for demand, supply, cost, technology or customer implications.",
    "whyItMatters": "10-K/10-Q 要重点抽取资本开支、库存、客户集中度、毛利和风险因素，不能只停留在 filing 本身。",
    "tags": [
      "AI",
      "Semiconductor Engineering"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 3,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Demand signal"
    ],
    "impactScore": 6,
    "titleZh": "",
    "titleEn": "Semiconductor Earnings Roundup: Revenue, Growth and Takeaways",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "中",
    "showByDefault": false,
    "lowValueReason": "弱信号文章未命中强业务落点"
  },
  {
    "id": "real_semiconductor_engineering_2026_08_17_800vdc_pushes_ai_power_design_from_grid_to_gate",
    "title": "800VDC Pushes AI Power Design From Grid To Gate",
    "signalCategory": "供应链",
    "industry": "核心零部件",
    "topic": "",
    "companies": [
      "Semiconductor Engineering"
    ],
    "importance": "高",
    "sourceId": "semiconductor_engineering",
    "sourceUrl": "https://semiengineering.com/800vdc-pushes-ai-power-design-from-grid-to-gate/",
    "publishedAt": "2026-08-17",
    "summary": "This update on 800VDC Pushes AI Power Design From Grid To Gate is relevant as an industry signal that should be reviewed for demand, supply, cost, technology or customer implications.",
    "whyItMatters": "核心零部件信号要落到供给瓶颈、BOM 成本、客户认证和量产节奏上，否则容易变成技术噪音。",
    "tags": [
      "AI",
      "Power",
      "Semiconductor Engineering"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 3,
    "sourceCategory": "discovery",
    "briefingValue": [],
    "impactScore": 12,
    "titleZh": "",
    "titleEn": "800VDC Pushes AI Power Design From Grid To Gate",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "中",
    "showByDefault": false
  },
  {
    "id": "real_semiconductor_engineering_2026_08_17_precision_under_pressure_rethinking_bond_reliability_i",
    "title": "Precision Under Pressure: Rethinking Bond Reliability In High-Density Semiconductor Test",
    "signalCategory": "产品",
    "industry": "核心零部件",
    "topic": "",
    "companies": [
      "Semiconductor Engineering"
    ],
    "importance": "低",
    "sourceId": "semiconductor_engineering",
    "sourceUrl": "https://semiengineering.com/precision-under-pressure-rethinking-bond-reliability-in-high-density-semiconductor-test/",
    "publishedAt": "2026-08-17",
    "summary": "This update on Precision Under Pressure: Rethinking Bond Reliability In High-Density Semiconductor Test is relevant as an industry signal that should be reviewed for demand, supply, cost, technology or customer implications.",
    "whyItMatters": "核心零部件信号要落到供给瓶颈、BOM 成本、客户认证和量产节奏上，否则容易变成技术噪音。",
    "tags": [
      "Semiconductor Engineering"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 3,
    "sourceCategory": "discovery",
    "briefingValue": [],
    "impactScore": 0,
    "titleZh": "",
    "titleEn": "Precision Under Pressure: Rethinking Bond Reliability In High-Density Semiconductor Test",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false
  },
  {
    "id": "real_semiconductor_engineering_2026_08_14_chip_industry_week_in_review",
    "title": "Chip Industry Week In Review",
    "signalCategory": "财报",
    "industry": "数据中心硬件",
    "topic": "",
    "companies": [
      "NVIDIA"
    ],
    "importance": "高",
    "sourceId": "semiconductor_engineering",
    "sourceUrl": "https://semiengineering.com/chip-industry-week-in-review-151/",
    "publishedAt": "2026-08-14",
    "summary": "This update on Chip Industry Week In Review is relevant as an industry signal that should be reviewed for demand, supply, cost, technology or customer implications.",
    "whyItMatters": "10-K/10-Q 要重点抽取资本开支、库存、客户集中度、毛利和风险因素，不能只停留在 filing 本身。",
    "tags": [
      "AI",
      "Data Center",
      "NVIDIA"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 3,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Supply signal",
      "Technology shift",
      "Customer move",
      "Luxshare business fit"
    ],
    "impactScore": 54,
    "titleZh": "",
    "titleEn": "Chip Industry Week In Review",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "中",
    "showByDefault": false,
    "lowValueReason": "弱信号文章未命中强业务落点"
  },
  {
    "id": "real_semiconductor_engineering_2026_08_13_the_1_megawatt_rack_debate",
    "title": "The 1-Megawatt Rack Debate",
    "signalCategory": "供应链",
    "industry": "数据中心硬件",
    "topic": "",
    "companies": [
      "Semiconductor Engineering"
    ],
    "importance": "高",
    "sourceId": "semiconductor_engineering",
    "sourceUrl": "https://semiengineering.com/the-1-megawatt-rack-debate/",
    "publishedAt": "2026-08-13",
    "summary": "This update on The 1-Megawatt Rack Debate is relevant as an industry signal that should be reviewed for demand, supply, cost, technology or customer implications.",
    "whyItMatters": "立讯需要把重点放在整机柜、供电、散热、高速线缆和连接器，而不是只看 GPU 或服务器品牌。",
    "tags": [
      "Server",
      "Semiconductor Engineering"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 3,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Luxshare business fit"
    ],
    "impactScore": 17,
    "titleZh": "",
    "titleEn": "The 1-Megawatt Rack Debate",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "高",
    "showByDefault": true
  },
  {
    "id": "real_tomshardware_2026_08_19_samsung_raises_advanced_foundry_prices_by_up_to_15_as_ai_demand_fil",
    "title": "Samsung raises advanced foundry prices by up to 15% as AI demand fills its 4nm lines, report claims — Chinese customers accepting the largest hikes",
    "signalCategory": "产品",
    "industry": "核心零部件",
    "topic": "",
    "companies": [
      "Samsung"
    ],
    "importance": "高",
    "sourceId": "tomshardware",
    "sourceUrl": "https://www.tomshardware.com/tech-industry/samsung-raises-advanced-foundry-prices-by-up-to-15-percent-as-ai-demand-fills-its-4nm-lines",
    "publishedAt": "2026-08-19",
    "summary": "This update on Samsung raises advanced foundry prices by up to 15% as AI demand fills its 4nm lines, report claims — Chinese customers accepting the largest hikes points to semiconductor supply-chain capacity or process progress that may affect upstream availability and technology roadmaps.",
    "whyItMatters": "先进封装和制程节奏会决定 AI 芯片交付能力，间接影响服务器整机和机柜组件订单能见度。",
    "tags": [
      "AI",
      "Samsung"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 2,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Demand signal",
      "Supply signal",
      "Cost signal"
    ],
    "impactScore": 30,
    "titleZh": "",
    "titleEn": "Samsung raises advanced foundry prices by up to 15% as AI demand fills its 4nm lines, report claims — Chinese customers accepting the largest hikes",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "高",
    "showByDefault": true
  },
  {
    "id": "real_tomshardware_2026_08_19_china_shifting_massive_ai_data_center_complexes_to_rural_provinces_",
    "title": "China shifting massive AI data center complexes to rural provinces to tap surplus energy — ‘Eastern Data, Western Computing’ strategy has Chinese tech giants Huawei and Tencent building AI infrastructure Guizhou",
    "signalCategory": "供应链",
    "industry": "数据中心硬件",
    "topic": "",
    "companies": [
      "Tom's Hardware"
    ],
    "importance": "高",
    "sourceId": "tomshardware",
    "sourceUrl": "https://www.tomshardware.com/tech-industry/data-centers/china-shifting-massive-ai-data-center-complexes-to-rural-provinces-to-tap-surplus-energy-eastern-data-western-computing-strategy-has-chinese-tech-giants-huawei-and-tencent-building-ai-infrastructure-guizhou",
    "publishedAt": "2026-08-19",
    "summary": "This data-center hardware update may affect server architecture, network or storage design and deployment requirements.",
    "whyItMatters": "立讯需要把重点放在整机柜、供电、散热、高速线缆和连接器，而不是只看 GPU 或服务器品牌。",
    "tags": [
      "AI",
      "Data Center",
      "Tom's Hardware"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 2,
    "sourceCategory": "discovery",
    "briefingValue": [],
    "impactScore": 13,
    "titleZh": "",
    "titleEn": "China shifting massive AI data center complexes to rural provinces to tap surplus energy — ‘Eastern Data, Western Computing’ strategy has Chinese tech giants Huawei and Tencent building AI infrastructure Guizhou",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "中",
    "showByDefault": false
  },
  {
    "id": "real_tomshardware_2026_08_19_you_can_now_buy_a_delidded_ryzen_9_9950x3d2_dual_edition_for_1_403_",
    "title": "You can now buy a delidded Ryzen 9 9950X3D2 Dual Edition for $1,403 — stripped dual-cache offering is $500 more expensive than regular version",
    "signalCategory": "产品",
    "industry": "核心零部件",
    "topic": "",
    "companies": [
      "Tom's Hardware"
    ],
    "importance": "低",
    "sourceId": "tomshardware",
    "sourceUrl": "https://www.tomshardware.com/pc-components/overclocking/you-can-now-buy-a-delidded-ryzen-9-9950x3d2-dual-edition-for-usd1-403-stripped-dual-cache-offering-is-usd500-more-expensive-than-regular-version",
    "publishedAt": "2026-08-19",
    "summary": "This update on You can now buy a delidded Ryzen 9 9950X3D2 Dual Edition for $1,403 — stripped dual-cache offering is $500 more expensive than regular version is relevant as an industry signal that should be reviewed for demand, supply, cost, technology or customer implications.",
    "whyItMatters": "核心零部件信号要落到供给瓶颈、BOM 成本、客户认证和量产节奏上，否则容易变成技术噪音。",
    "tags": [
      "Tom's Hardware"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 2,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Cost signal"
    ],
    "impactScore": 0,
    "titleZh": "",
    "titleEn": "You can now buy a delidded Ryzen 9 9950X3D2 Dual Edition for $1,403 — stripped dual-cache offering is $500 more expensive than regular version",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false
  },
  {
    "id": "real_tomshardware_2026_08_19_hacker_leaks_gta_vi_gameplay_and_map_to_protest_digital_only_releas",
    "title": "Hacker leaks GTA VI gameplay and map to protest digital-only release — claims pre-orders are a legacy of physical game releases",
    "signalCategory": "产品",
    "industry": "3C 产品",
    "topic": "",
    "companies": [
      "Tom's Hardware"
    ],
    "importance": "低",
    "sourceId": "tomshardware",
    "sourceUrl": "https://www.tomshardware.com/video-games/hacker-leaks-gta-vi-gameplay-and-map-to-protest-digital-only-release-claims-pre-orders-are-a-legacy-of-physical-game-releases",
    "publishedAt": "2026-08-19",
    "summary": "This update on Hacker leaks GTA VI gameplay and map to protest digital-only release — claims pre-orders are a legacy of physical game releases is relevant as a supply-chain signal around capacity, production ramp or supplier positioning.",
    "whyItMatters": "产品信号只有在带来规格升级、备货变化或供应商切换时，才应进入管理层优先阅读。",
    "tags": [
      "AI",
      "Tom's Hardware"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 2,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Demand signal",
      "Risk event"
    ],
    "impactScore": 0,
    "titleZh": "",
    "titleEn": "Hacker leaks GTA VI gameplay and map to protest digital-only release — claims pre-orders are a legacy of physical game releases",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false,
    "lowValueReason": "技术论文或研究合集，管理层决策价值低"
  },
  {
    "id": "real_tomshardware_2026_08_19_google_to_stop_making_pixel_devices_in_china_report_claims_india_an",
    "title": "Google to stop making Pixel devices in China, report claims — India and Vietnam prime candidates for manufacturing shift owing to Beijing-Washington tensions",
    "signalCategory": "产品",
    "industry": "3C 产品",
    "topic": "",
    "companies": [
      "Google"
    ],
    "importance": "高",
    "sourceId": "tomshardware",
    "sourceUrl": "https://www.tomshardware.com/phones/google-to-stop-making-pixel-devices-in-china-report-claims-india-and-vietnam-prime-candidates-for-manufacturing-shift-owing-to-beijing-washington-tensions",
    "publishedAt": "2026-08-19",
    "summary": "This update on Google to stop making Pixel devices in China, report claims — India and Vietnam prime candidates for manufacturing shift owing to Beijing-Washington tensions is relevant as an industry signal that should be reviewed for demand, supply, cost, technology or customer implications.",
    "whyItMatters": "产品信号只有在带来规格升级、备货变化或供应商切换时，才应进入管理层优先阅读。",
    "tags": [
      "AI",
      "Smartphone",
      "Google"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 2,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Customer move"
    ],
    "impactScore": 19,
    "titleZh": "",
    "titleEn": "Google to stop making Pixel devices in China, report claims — India and Vietnam prime candidates for manufacturing shift owing to Beijing-Washington tensions",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "中",
    "showByDefault": true
  },
  {
    "id": "real_tomshardware_2026_08_19_jason_kelce_led_marketing_campaign_asks_beer_drinkers_to_send_their",
    "title": "Jason Kelce-led marketing campaign asks beer drinkers to send their pee to AI data centers — Liquid Death and Garage Beer skit claims 'AI data centers waste millions of gallons of water'",
    "signalCategory": "供应链",
    "industry": "数据中心硬件",
    "topic": "",
    "companies": [
      "Tom's Hardware"
    ],
    "importance": "低",
    "sourceId": "tomshardware",
    "sourceUrl": "https://www.tomshardware.com/tech-industry/data-centers/jason-kelce-led-marketing-campaign-asks-beer-drinkers-to-send-their-pee-to-ai-data-centers-liquid-death-and-garage-beer-skit-claims-ai-data-centers-waste-millions-of-gallons-of-water",
    "publishedAt": "2026-08-19",
    "summary": "This update on Jason Kelce-led marketing campaign asks beer drinkers to send their pee to AI data centers — Liquid Death and Garage Beer skit claims 'AI data centers waste millions of gallons of water' is relevant as an industry signal that should be reviewed for demand, supply, cost, technology or customer implications.",
    "whyItMatters": "立讯需要把重点放在整机柜、供电、散热、高速线缆和连接器，而不是只看 GPU 或服务器品牌。",
    "tags": [
      "AI",
      "Data Center",
      "Cooling",
      "Tom's Hardware"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 2,
    "sourceCategory": "discovery",
    "briefingValue": [],
    "impactScore": 0,
    "titleZh": "",
    "titleEn": "Jason Kelce-led marketing campaign asks beer drinkers to send their pee to AI data centers — Liquid Death and Garage Beer skit claims 'AI data centers waste millions of gallons of water'",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false
  },
  {
    "id": "real_tomshardware_2026_08_19_ajinomoto_reportedly_cuts_critical_chip_packaging_film_supply_to_ch",
    "title": "Ajinomoto reportedly cuts critical chip packaging film supply to China by 30% as domestic substitutes race to qualify — ABF restriction comes following Beijing's rare earth export curbs",
    "signalCategory": "供应链",
    "industry": "核心零部件",
    "topic": "",
    "companies": [
      "Tom's Hardware"
    ],
    "importance": "中",
    "sourceId": "tomshardware",
    "sourceUrl": "https://www.tomshardware.com/tech-industry/semiconductors/ajinomoto-reportedly-cuts-abf-chip-packaging-film-supply-to-china-by-30-percent",
    "publishedAt": "2026-08-19",
    "summary": "This semiconductor update points to process, packaging or wafer-supply changes that may affect upstream availability and technology roadmaps.",
    "whyItMatters": "核心零部件信号要落到供给瓶颈、BOM 成本、客户认证和量产节奏上，否则容易变成技术噪音。",
    "tags": [
      "AI",
      "Tom's Hardware"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 2,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Supply signal"
    ],
    "impactScore": 5,
    "titleZh": "",
    "titleEn": "Ajinomoto reportedly cuts critical chip packaging film supply to China by 30% as domestic substitutes race to qualify — ABF restriction comes following Beijing's rare earth export curbs",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "中",
    "showByDefault": true
  },
  {
    "id": "real_tomshardware_2026_08_19_microsd_card_torture_test_writes_133_petabytes_of_data_across_351_c",
    "title": "MicroSD card torture test writes 133 petabytes of data across 351 cards over three years — cards tested to failure reveal SanDisk as the outlier with 6 failures of the 7 tested",
    "signalCategory": "产品",
    "industry": "3C 产品",
    "topic": "",
    "companies": [
      "Tom's Hardware"
    ],
    "importance": "低",
    "sourceId": "tomshardware",
    "sourceUrl": "https://www.tomshardware.com/pc-components/microsd-cards/microsd-card-testing-database-celebrates-third-anniversary-with-133-petabytes-of-data-written-across-4-6-million-cycles-hundreds-of-cards-tested-to-failure-reveal-sandisk-as-the-outlier-with-6-failures-of-the-7-tested",
    "publishedAt": "2026-08-19",
    "summary": "This update on MicroSD card torture test writes 133 petabytes of data across 351 cards over three years — cards tested to failure reveal SanDisk as the outlier with 6 failures of the 7 tested is relevant as an industry signal that should be reviewed for demand, supply, cost, technology or customer implications.",
    "whyItMatters": "产品信号只有在带来规格升级、备货变化或供应商切换时，才应进入管理层优先阅读。",
    "tags": [
      "AI",
      "Tom's Hardware"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 2,
    "sourceCategory": "discovery",
    "briefingValue": [],
    "impactScore": 0,
    "titleZh": "",
    "titleEn": "MicroSD card torture test writes 133 petabytes of data across 351 cards over three years — cards tested to failure reveal SanDisk as the outlier with 6 failures of the 7 tested",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false
  },
  {
    "id": "real_techpowerup_2026_08_19_pretty_cool_games_launches_as_new_studio_from_human_fall_flat_devs",
    "title": "Pretty Cool Games Launches As New Studio From \"Human: Fall Flat\" Devs",
    "signalCategory": "产品",
    "industry": "3C 产品",
    "topic": "",
    "companies": [
      "TechPowerUp"
    ],
    "importance": "低",
    "sourceId": "techpowerup",
    "sourceUrl": "https://www.techpowerup.com/351733/pretty-cool-games-launches-as-new-studio-from-human-fall-flat-devs",
    "publishedAt": "2026-08-19",
    "summary": "This update on Pretty Cool Games Launches As New Studio From \"Human: Fall Flat\" Devs is relevant as an industry signal that should be reviewed for demand, supply, cost, technology or customer implications.",
    "whyItMatters": "产品信号只有在带来规格升级、备货变化或供应商切换时，才应进入管理层优先阅读。",
    "tags": [
      "AI",
      "TechPowerUp"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 2,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Demand signal",
      "Capital allocation"
    ],
    "impactScore": 0,
    "titleZh": "",
    "titleEn": "Pretty Cool Games Launches As New Studio From \"Human: Fall Flat\" Devs",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false,
    "lowValueReason": "命中默认 feed 禁入弱信号且缺少强产业信号"
  },
  {
    "id": "real_techpowerup_2026_08_19_get_word_excel_powerpoint_and_more_for_life_for_55",
    "title": "Get Word, Excel, PowerPoint, and More for Life for $55",
    "signalCategory": "供应链",
    "industry": "3C 产品",
    "topic": "",
    "companies": [
      "Microsoft"
    ],
    "importance": "高",
    "sourceId": "techpowerup",
    "sourceUrl": "https://www.techpowerup.com/351664/get-word-excel-powerpoint-and-more-for-life-for-usd-55",
    "publishedAt": "2026-08-19",
    "summary": "This update on Get Word, Excel, PowerPoint, and More for Life for $55 is relevant as an industry signal that should be reviewed for demand, supply, cost, technology or customer implications.",
    "whyItMatters": "产品信号只有在带来规格升级、备货变化或供应商切换时，才应进入管理层优先阅读。",
    "tags": [
      "Cloud",
      "Power",
      "Microsoft"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 2,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Cost signal",
      "Customer move"
    ],
    "impactScore": 49,
    "titleZh": "",
    "titleEn": "Get Word, Excel, PowerPoint, and More for Life for $55",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "中",
    "showByDefault": true
  },
  {
    "id": "real_techpowerup_2026_08_19_cachyos_and_almalinux_beat_out_windows_11_in_workstation_benchmarks",
    "title": "CachyOS and AlmaLinux Beat out Windows 11 in Workstation Benchmarks",
    "signalCategory": "产品",
    "industry": "3C 产品",
    "topic": "",
    "companies": [
      "TechPowerUp"
    ],
    "importance": "低",
    "sourceId": "techpowerup",
    "sourceUrl": "https://www.techpowerup.com/351732/cachyos-and-almalinux-beat-out-windows-11-in-workstation-benchmarks",
    "publishedAt": "2026-08-19",
    "summary": "This update on CachyOS and AlmaLinux Beat out Windows 11 in Workstation Benchmarks is relevant as an industry signal that should be reviewed for demand, supply, cost, technology or customer implications.",
    "whyItMatters": "产品信号只有在带来规格升级、备货变化或供应商切换时，才应进入管理层优先阅读。",
    "tags": [
      "AI",
      "TechPowerUp"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 2,
    "sourceCategory": "discovery",
    "briefingValue": [],
    "impactScore": 0,
    "titleZh": "",
    "titleEn": "CachyOS and AlmaLinux Beat out Windows 11 in Workstation Benchmarks",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false
  },
  {
    "id": "real_techpowerup_2026_08_19_no_man_039_s_sky_and_palworld_tease_collaboration",
    "title": "No Man&#039;s Sky and Palworld Tease Collaboration",
    "signalCategory": "公司动态",
    "industry": "3C 产品",
    "topic": "",
    "companies": [
      "Nothing"
    ],
    "importance": "低",
    "sourceId": "techpowerup",
    "sourceUrl": "https://www.techpowerup.com/351729/no-mans-sky-and-palworld-tease-collaboration",
    "publishedAt": "2026-08-19",
    "summary": "This update on No Man&#039;s Sky and Palworld Tease Collaboration is relevant as an industry signal that should be reviewed for demand, supply, cost, technology or customer implications.",
    "whyItMatters": "公司动态需要判断是否改变客户关系、技术路线或订单归属；没有落到这些变量上就不应放大解读。",
    "tags": [
      "AI",
      "Nothing"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 2,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Competitor move"
    ],
    "impactScore": 0,
    "titleZh": "",
    "titleEn": "No Man&#039;s Sky and Palworld Tease Collaboration",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false,
    "lowValueReason": "技术论文或研究合集，管理层决策价值低"
  },
  {
    "id": "real_techpowerup_2026_08_19_windows_11_adds_per_app_control_for_microphone_location_and_camera_a",
    "title": "Windows 11 Adds Per-App Control for Microphone, Location, and Camera Access",
    "signalCategory": "产品",
    "industry": "3C 产品",
    "topic": "",
    "companies": [
      "Microsoft"
    ],
    "importance": "低",
    "sourceId": "techpowerup",
    "sourceUrl": "https://www.techpowerup.com/351708/windows-11-adds-per-app-control-for-microphone-location-and-camera-access",
    "publishedAt": "2026-08-19",
    "summary": "This update on Windows 11 Adds Per-App Control for Microphone, Location, and Camera Access is relevant as an industry signal that should be reviewed for demand, supply, cost, technology or customer implications.",
    "whyItMatters": "产品信号只有在带来规格升级、备货变化或供应商切换时，才应进入管理层优先阅读。",
    "tags": [
      "AI",
      "Microsoft"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 2,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Customer move",
      "Competitor move",
      "Luxshare business fit"
    ],
    "impactScore": 0,
    "titleZh": "",
    "titleEn": "Windows 11 Adds Per-App Control for Microphone, Location, and Camera Access",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false
  },
  {
    "id": "real_techpowerup_2026_08_18_framework_laptop_12_gets_intel_core_series_3_cpus_and_thunderbolt_4_",
    "title": "Framework Laptop 12 Gets Intel Core Series 3 CPUs and Thunderbolt 4 Upgrade",
    "signalCategory": "供应链",
    "industry": "核心零部件",
    "topic": "",
    "companies": [
      "Intel"
    ],
    "importance": "低",
    "sourceId": "techpowerup",
    "sourceUrl": "https://www.techpowerup.com/351693/framework-laptop-12-gets-intel-core-series-3-cpus-and-thunderbolt-4-upgrade",
    "publishedAt": "2026-08-18",
    "summary": "This update on Framework Laptop 12 Gets Intel Core Series 3 CPUs and Thunderbolt 4 Upgrade is relevant as an industry signal that should be reviewed for demand, supply, cost, technology or customer implications.",
    "whyItMatters": "核心零部件信号要落到供给瓶颈、BOM 成本、客户认证和量产节奏上，否则容易变成技术噪音。",
    "tags": [
      "AI",
      "GPU",
      "Intel"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 2,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Demand signal",
      "Supply signal"
    ],
    "impactScore": 0,
    "titleZh": "",
    "titleEn": "Framework Laptop 12 Gets Intel Core Series 3 CPUs and Thunderbolt 4 Upgrade",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false
  },
  {
    "id": "real_techpowerup_2026_08_18_zalman_launches_new_cnps_series_dual_tower_cpu_air_coolers",
    "title": "Zalman Launches New CNPS Series Dual-Tower CPU Air Coolers",
    "signalCategory": "供应链",
    "industry": "核心零部件",
    "topic": "",
    "companies": [
      "TechPowerUp"
    ],
    "importance": "低",
    "sourceId": "techpowerup",
    "sourceUrl": "https://www.techpowerup.com/351692/zalman-launches-new-cnps-series-dual-tower-cpu-air-coolers",
    "publishedAt": "2026-08-18",
    "summary": "This update on Zalman Launches New CNPS Series Dual-Tower CPU Air Coolers is relevant as an industry signal that should be reviewed for demand, supply, cost, technology or customer implications.",
    "whyItMatters": "核心零部件信号要落到供给瓶颈、BOM 成本、客户认证和量产节奏上，否则容易变成技术噪音。",
    "tags": [
      "AI",
      "HBM",
      "TechPowerUp"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 2,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Luxshare business fit"
    ],
    "impactScore": 3,
    "titleZh": "",
    "titleEn": "Zalman Launches New CNPS Series Dual-Tower CPU Air Coolers",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false
  },
  {
    "id": "real_techpowerup_2026_08_18_intel_razor_lake_to_use_tsmc_039_s_n2x_node_brings_bllc_to_laptop_sk",
    "title": "Intel \"Razor Lake\" to Use TSMC&#039;s N2X Node, Brings bLLC to Laptop SKUs",
    "signalCategory": "供应链",
    "industry": "核心零部件",
    "topic": "",
    "companies": [
      "AMD",
      "Intel",
      "TSMC"
    ],
    "importance": "低",
    "sourceId": "techpowerup",
    "sourceUrl": "https://www.techpowerup.com/351684/intel-razor-lake-to-use-tsmcs-n2x-node-brings-bllc-to-laptop-skus",
    "publishedAt": "2026-08-18",
    "summary": "This update on Intel \"Razor Lake\" to Use TSMC&#039;s N2X Node, Brings bLLC to Laptop SKUs points to semiconductor supply-chain capacity or process progress that may affect upstream availability and technology roadmaps.",
    "whyItMatters": "先进封装和制程节奏会决定 AI 芯片交付能力，间接影响服务器整机和机柜组件订单能见度。",
    "tags": [
      "AI",
      "Power",
      "AMD",
      "Intel"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 2,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Supply signal",
      "Cost signal",
      "Customer move",
      "Risk event"
    ],
    "impactScore": 0,
    "titleZh": "",
    "titleEn": "Intel \"Razor Lake\" to Use TSMC&#039;s N2X Node, Brings bLLC to Laptop SKUs",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false
  },
  {
    "id": "real_servethehome_2026_08_19_cerebras_intros_faster_wse_3_turbo_processor_and_first_rack_scale_c",
    "title": "Cerebras Intros Faster WSE-3 Turbo Processor and First Rack-Scale CS-4 System",
    "signalCategory": "供应链",
    "industry": "数据中心硬件",
    "topic": "",
    "companies": [
      "ServeTheHome"
    ],
    "importance": "高",
    "sourceId": "servethehome",
    "sourceUrl": "https://www.servethehome.com/cerebras-intros-faster-wse-3-turbo-processor-and-first-rack-scale-cs-4-system/",
    "publishedAt": "2026-08-19",
    "summary": "This update on Cerebras Intros Faster WSE-3 Turbo Processor and First Rack-Scale CS-4 System points to semiconductor supply-chain capacity or process progress that may affect upstream availability and technology roadmaps.",
    "whyItMatters": "立讯需要把重点放在整机柜、供电、散热、高速线缆和连接器，而不是只看 GPU 或服务器品牌。",
    "tags": [
      "AI",
      "Server",
      "Cloud",
      "Power",
      "ServeTheHome"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 4,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Technology shift",
      "Luxshare business fit"
    ],
    "impactScore": 37,
    "titleZh": "",
    "titleEn": "Cerebras Intros Faster WSE-3 Turbo Processor and First Rack-Scale CS-4 System",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "高",
    "showByDefault": true
  },
  {
    "id": "real_servethehome_2026_08_14_160_bay_nvme_ssd_4u_server_shown_at_fms_2026_supermicro_asg_4116s_n",
    "title": "160-bay NVMe SSD 4U Server Shown at FMS 2026 Supermicro ASG-4116S-NU160R",
    "signalCategory": "供应链",
    "industry": "数据中心硬件",
    "topic": "",
    "companies": [
      "Supermicro"
    ],
    "importance": "低",
    "sourceId": "servethehome",
    "sourceUrl": "https://www.servethehome.com/160-bay-nvme-ssd-4u-server-shown-at-fms-2026-supermicro-asg-4116s-nu160r/",
    "publishedAt": "2026-08-14",
    "summary": "This update on 160-bay NVMe SSD 4U Server Shown at FMS 2026 Supermicro ASG-4116S-NU160R signals memory-supply pressure or architecture change that can affect AI servers, data-center hardware and BOM planning.",
    "whyItMatters": "存储供给被 AI 数据中心吸走时，会同时影响服务器 BOM 和消费电子备货成本，需看缺货是否传导到客户排产。",
    "tags": [
      "Server",
      "Storage",
      "Supermicro"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 4,
    "sourceCategory": "discovery",
    "briefingValue": [],
    "impactScore": 0,
    "titleZh": "",
    "titleEn": "160-bay NVMe SSD 4U Server Shown at FMS 2026 Supermicro ASG-4116S-NU160R",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false
  },
  {
    "id": "real_storagereview_2026_08_19_best_local_llm_tools_in_2026_runtimes_apps_and_agents",
    "title": "Best Local LLM Tools in 2026: Runtimes, Apps, and Agents",
    "signalCategory": "产品",
    "industry": "3C 产品",
    "topic": "",
    "companies": [
      "StorageReview"
    ],
    "importance": "中",
    "sourceId": "storagereview",
    "sourceUrl": "https://www.storagereview.com/best/local-llm-tools",
    "publishedAt": "2026-08-19",
    "summary": "This update on Best Local LLM Tools in 2026: Runtimes, Apps, and Agents is relevant as an industry signal that should be reviewed for demand, supply, cost, technology or customer implications.",
    "whyItMatters": "产品信号只有在带来规格升级、备货变化或供应商切换时，才应进入管理层优先阅读。",
    "tags": [
      "Storage",
      "StorageReview"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 4,
    "sourceCategory": "discovery",
    "briefingValue": [],
    "impactScore": 6,
    "titleZh": "",
    "titleEn": "Best Local LLM Tools in 2026: Runtimes, Apps, and Agents",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "中",
    "showByDefault": false
  },
  {
    "id": "real_storagereview_2026_08_19_nvidia_openai_and_sb_energy_detail_the_8_it_gw_ports_pike_technolo",
    "title": "NVIDIA, OpenAI, and SB Energy Detail the 8 IT-GW PORTS-Pike Technology Campus and Its $105 Billion Credit Backstop",
    "signalCategory": "公司动态",
    "industry": "数据中心硬件",
    "topic": "",
    "companies": [
      "NVIDIA"
    ],
    "importance": "高",
    "sourceId": "storagereview",
    "sourceUrl": "https://www.storagereview.com/news/nvidia-openai-and-sb-energy-detail-the-8-it-gw-ports-pike-technology-campus-and-its-105-billion-credit-backstop",
    "publishedAt": "2026-08-19",
    "summary": "This update on NVIDIA, OpenAI, and SB Energy Detail the 8 IT-GW PORTS-Pike Technology Campus and Its $105 Billion Credit Backstop is relevant as an industry signal that should be reviewed for demand, supply, cost, technology or customer implications.",
    "whyItMatters": "公司动态需要判断是否改变客户关系、技术路线或订单归属；没有落到这些变量上就不应放大解读。",
    "tags": [
      "AI",
      "Storage",
      "NVIDIA"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 4,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Customer move",
      "Capital allocation"
    ],
    "impactScore": 28,
    "titleZh": "",
    "titleEn": "NVIDIA, OpenAI, and SB Energy Detail the 8 IT-GW PORTS-Pike Technology Campus and Its $105 Billion Credit Backstop",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "中",
    "showByDefault": true
  },
  {
    "id": "real_storagereview_2026_08_19_stack_automation_by_quali_goes_ga_as_a_cisco_exclusive_promising_r",
    "title": "Stack Automation by Quali Goes GA as a Cisco Exclusive, Promising Rack to Application in Hours",
    "signalCategory": "供应链",
    "industry": "数据中心硬件",
    "topic": "",
    "companies": [
      "StorageReview"
    ],
    "importance": "高",
    "sourceId": "storagereview",
    "sourceUrl": "https://www.storagereview.com/news/stack-automation-by-quali",
    "publishedAt": "2026-08-19",
    "summary": "This update on Stack Automation by Quali Goes GA as a Cisco Exclusive, Promising Rack to Application in Hours is relevant as an industry signal that should be reviewed for demand, supply, cost, technology or customer implications.",
    "whyItMatters": "立讯需要把重点放在整机柜、供电、散热、高速线缆和连接器，而不是只看 GPU 或服务器品牌。",
    "tags": [
      "AI",
      "Server",
      "Storage",
      "StorageReview"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 4,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Luxshare business fit"
    ],
    "impactScore": 27,
    "titleZh": "",
    "titleEn": "Stack Automation by Quali Goes GA as a Cisco Exclusive, Promising Rack to Application in Hours",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "高",
    "showByDefault": true
  },
  {
    "id": "real_storagereview_2026_08_19_ibm_links_two_cryogenic_modules_below_15_millikelvin_on_the_path_t",
    "title": "IBM Links Two Cryogenic Modules Below 15 Millikelvin on the Path to Its 2029 Fault-Tolerant Quantum Computer",
    "signalCategory": "产品",
    "industry": "3C 产品",
    "topic": "",
    "companies": [
      "StorageReview"
    ],
    "importance": "高",
    "sourceId": "storagereview",
    "sourceUrl": "https://www.storagereview.com/news/ibm-links-two-cryogenic-modules-below-15-millikelvin-on-the-path-to-its-2029-fault-tolerant-quantum-computer",
    "publishedAt": "2026-08-19",
    "summary": "This update on IBM Links Two Cryogenic Modules Below 15 Millikelvin on the Path to Its 2029 Fault-Tolerant Quantum Computer is relevant as an industry signal that should be reviewed for demand, supply, cost, technology or customer implications.",
    "whyItMatters": "产品信号只有在带来规格升级、备货变化或供应商切换时，才应进入管理层优先阅读。",
    "tags": [
      "Storage",
      "StorageReview"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 4,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Competitor move"
    ],
    "impactScore": 11,
    "titleZh": "",
    "titleEn": "IBM Links Two Cryogenic Modules Below 15 Millikelvin on the Path to Its 2029 Fault-Tolerant Quantum Computer",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "中",
    "showByDefault": true
  },
  {
    "id": "real_storagereview_2026_08_18_sandisk_tapes_out_its_first_hbf_memory_die_targets_2027_for_infere",
    "title": "Sandisk Tapes Out Its First HBF Memory Die, Targets 2027 for Inference Product Samples",
    "signalCategory": "供应链",
    "industry": "数据中心硬件",
    "topic": "",
    "companies": [
      "StorageReview"
    ],
    "importance": "低",
    "sourceId": "storagereview",
    "sourceUrl": "https://www.storagereview.com/news/sandisk-tapes-out-its-first-hbf-memory-die-targets-2027-for-inference-product-samples",
    "publishedAt": "2026-08-18",
    "summary": "This update on Sandisk Tapes Out Its First HBF Memory Die, Targets 2027 for Inference Product Samples signals memory-supply pressure or architecture change that can affect AI servers, data-center hardware and BOM planning.",
    "whyItMatters": "存储供给被 AI 数据中心吸走时，会同时影响服务器 BOM 和消费电子备货成本，需看缺货是否传导到客户排产。",
    "tags": [
      "HBM",
      "Cloud",
      "Storage",
      "StorageReview"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 4,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Capital allocation"
    ],
    "impactScore": 0,
    "titleZh": "",
    "titleEn": "Sandisk Tapes Out Its First HBF Memory Die, Targets 2027 for Inference Product Samples",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false
  },
  {
    "id": "real_storagereview_2026_08_18_enterprise_ssd_prices_run_at_6_5x_last_year_vdura_pegs_a_30tb_tlc_",
    "title": "Enterprise SSD Prices Run at 6.5x Last Year: VDURA Pegs a 30TB TLC Drive at $22,600",
    "signalCategory": "产品",
    "industry": "3C 产品",
    "topic": "",
    "companies": [
      "StorageReview"
    ],
    "importance": "低",
    "sourceId": "storagereview",
    "sourceUrl": "https://www.storagereview.com/news/enterprise-ssd-prices-run-at-6-5x-last-year-vdura-pegs-a-30tb-tlc-drive-at-22600",
    "publishedAt": "2026-08-18",
    "summary": "This update on Enterprise SSD Prices Run at 6.5x Last Year: VDURA Pegs a 30TB TLC Drive at $22,600 signals memory-supply pressure or architecture change that can affect AI servers, data-center hardware and BOM planning.",
    "whyItMatters": "存储供给被 AI 数据中心吸走时，会同时影响服务器 BOM 和消费电子备货成本，需看缺货是否传导到客户排产。",
    "tags": [
      "AI",
      "Storage",
      "StorageReview"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 4,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Cost signal"
    ],
    "impactScore": 0,
    "titleZh": "",
    "titleEn": "Enterprise SSD Prices Run at 6.5x Last Year: VDURA Pegs a 30TB TLC Drive at $22,600",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "低",
    "showByDefault": false
  },
  {
    "id": "real_storagereview_2026_08_18_sk_hynix_and_solidigm_split_the_nand_map_54_trillion_won_at_home_a",
    "title": "SK hynix and Solidigm Split the NAND Map: 54 Trillion Won at Home, a Reported Dalian Fab 2 Restart in China",
    "signalCategory": "供应链",
    "industry": "核心零部件",
    "topic": "",
    "companies": [
      "SK hynix"
    ],
    "importance": "高",
    "sourceId": "storagereview",
    "sourceUrl": "https://www.storagereview.com/news/sk-hynix-and-solidigm-split-the-nand-map-54-trillion-won-at-home-a-reported-dalian-fab-2-restart-in-china",
    "publishedAt": "2026-08-18",
    "summary": "This update on SK hynix and Solidigm Split the NAND Map: 54 Trillion Won at Home, a Reported Dalian Fab 2 Restart in China signals memory-supply pressure or architecture change that can affect AI servers, data-center hardware and BOM planning.",
    "whyItMatters": "存储供给被 AI 数据中心吸走时，会同时影响服务器 BOM 和消费电子备货成本，需看缺货是否传导到客户排产。",
    "tags": [
      "AI",
      "HBM",
      "Storage",
      "SK hynix"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 4,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Demand signal",
      "Supply signal",
      "Risk event",
      "Capital allocation"
    ],
    "impactScore": 30,
    "titleZh": "",
    "titleEn": "SK hynix and Solidigm Split the NAND Map: 54 Trillion Won at Home, a Reported Dalian Fab 2 Restart in China",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "高",
    "showByDefault": true
  },
  {
    "id": "real_storagereview_2026_08_18_amd_ai_energy_efficiency_up_4x_since_2024_ahead_of_pace_on_its_20x",
    "title": "AMD AI Energy Efficiency Up 4x Since 2024, Ahead of Pace on Its 20x-by-2030 Rack-Scale Goal",
    "signalCategory": "供应链",
    "industry": "数据中心硬件",
    "topic": "",
    "companies": [
      "AMD"
    ],
    "importance": "高",
    "sourceId": "storagereview",
    "sourceUrl": "https://www.storagereview.com/news/amd-ai-energy-efficiency-up-4x-since-2024-ahead-of-pace-on-its-20x-by-2030-rack-scale-goal",
    "publishedAt": "2026-08-18",
    "summary": "This update on AMD AI Energy Efficiency Up 4x Since 2024, Ahead of Pace on Its 20x-by-2030 Rack-Scale Goal is relevant as an industry signal that should be reviewed for demand, supply, cost, technology or customer implications.",
    "whyItMatters": "立讯需要把重点放在整机柜、供电、散热、高速线缆和连接器，而不是只看 GPU 或服务器品牌。",
    "tags": [
      "AI",
      "Server",
      "Cloud",
      "Storage",
      "AMD"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "en",
    "sourceWeight": 4,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Technology shift",
      "Customer move",
      "Luxshare business fit"
    ],
    "impactScore": 45,
    "titleZh": "",
    "titleEn": "AMD AI Energy Efficiency Up 4x Since 2024, Ahead of Pace on Its 20x-by-2030 Rack-Scale Goal",
    "summaryZh": "",
    "summaryEn": "",
    "whyZh": "",
    "whyEn": "",
    "relevance": "高",
    "showByDefault": true
  },
  {
    "id": "real_ithome_2026_08_19_8_elite_gen_6_pro",
    "title": "骁龙 8 Elite Gen 6/Pro？高通称将在骁龙峰会推出两款芯片",
    "signalCategory": "产品",
    "industry": "3C 产品",
    "topic": "",
    "companies": [
      "Qualcomm"
    ],
    "importance": "低",
    "sourceId": "ithome",
    "sourceUrl": "https://www.ithome.com/0/991/876.htm",
    "publishedAt": "2026-08-19",
    "summary": "围绕“骁龙 8 Elite Gen 6/Pro？高通称将在骁龙峰会推出两款芯片”，这条信息已命中行业硬信号，需要结合原文确认其对需求、供给、成本或客户动作的影响。",
    "whyItMatters": "产品信号只有在带来规格升级、备货变化或供应商切换时，才应进入管理层优先阅读。",
    "tags": [
      "Qualcomm"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "zh",
    "sourceWeight": 3,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Demand signal",
      "Risk event"
    ],
    "impactScore": 0,
    "titleZh": "骁龙 8 Elite Gen 6/Pro？高通称将在骁龙峰会推出两款芯片",
    "titleEn": "骁龙 8 Elite Gen 6/Pro？高通称将在骁龙峰会推出两款芯片",
    "summaryZh": "围绕“骁龙 8 Elite Gen 6/Pro？高通称将在骁龙峰会推出两款芯片”，这条信息已命中行业硬信号，需要结合原文确认其对需求、供给、成本或客户动作的影响。",
    "summaryEn": "围绕“骁龙 8 Elite Gen 6/Pro？高通称将在骁龙峰会推出两款芯片”，这条信息已命中行业硬信号，需要结合原文确认其对需求、供给、成本或客户动作的影响。",
    "whyZh": "产品信号只有在带来规格升级、备货变化或供应商切换时，才应进入管理层优先阅读。",
    "whyEn": "For Luxshare, track this only if it changes orders, specifications, qualification paths, customer allocation, or supply risk.",
    "relevance": "低",
    "showByDefault": false
  },
  {
    "id": "real_ithome_2026_08_19_airpods_pro_3_2027",
    "title": "古尔曼：苹果带摄像头的 AirPods Pro 3 增强版耳机延至 2027 年发布",
    "signalCategory": "产品",
    "industry": "3C 产品",
    "topic": "",
    "companies": [
      "Apple",
      "Meta"
    ],
    "importance": "高",
    "sourceId": "ithome",
    "sourceUrl": "https://www.ithome.com/0/991/874.htm",
    "publishedAt": "2026-08-19",
    "summary": "古尔曼在博文中认为，苹果公司目前正在研发 B790 和 B798 两款耳机。",
    "whyItMatters": "苹果链信号优先看两点：端侧硬件规格是否升级，以及云端 AI 投入是否带来新的服务器和互连需求。",
    "tags": [
      "AI",
      "Apple",
      "Meta"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "zh",
    "sourceWeight": 3,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Supply signal",
      "Customer move"
    ],
    "impactScore": 41,
    "titleZh": "古尔曼：苹果带摄像头的 AirPods Pro 3 增强版耳机延至 2027 年发布",
    "titleEn": "古尔曼：苹果带摄像头的 AirPods Pro 3 增强版耳机延至 2027 年发布",
    "summaryZh": "古尔曼在博文中认为，苹果公司目前正在研发 B790 和 B798 两款耳机。",
    "summaryEn": "古尔曼在博文中认为，苹果公司目前正在研发 B790 和 B798 两款耳机。",
    "whyZh": "苹果链信号优先看两点：端侧硬件规格是否升级，以及云端 AI 投入是否带来新的服务器和互连需求。",
    "whyEn": "For the Apple chain, the key is whether new device form factors change component specifications, assembly yield, or supplier qualification.",
    "relevance": "中",
    "showByDefault": false,
    "lowValueReason": "IT之家文章缺少明确硬信号或命中低价值内容"
  },
  {
    "id": "real_ithome_2026_08_19_ai",
    "title": "特朗普力挺 AI 数据中心：反对建设的州和社区将被甩在后面",
    "signalCategory": "产品",
    "industry": "数据中心硬件",
    "topic": "",
    "companies": [
      "Meta"
    ],
    "importance": "低",
    "sourceId": "ithome",
    "sourceUrl": "https://www.ithome.com/0/991/871.htm",
    "publishedAt": "2026-08-19",
    "summary": "特朗普当地时间周三在一场聚焦加密货币的活动结束后对记者表示：“我想说，它可能需要在公共关系方面得到一些帮助。 ” 特朗普明确表示，无论公众对数据中心的观感如何，他仍然坚定支持 AI 产业，以及 AI 企业为训练未来模型、满足预期市场需求而需要建设的相关设施。",
    "whyItMatters": "立讯需要把重点放在整机柜、供电、散热、高速线缆和连接器，而不是只看 GPU 或服务器品牌。",
    "tags": [
      "AI",
      "Cooling",
      "Meta"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "zh",
    "sourceWeight": 3,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Demand signal",
      "Customer move",
      "Risk event"
    ],
    "impactScore": 0,
    "titleZh": "特朗普力挺 AI 数据中心：反对建设的州和社区将被甩在后面",
    "titleEn": "特朗普力挺 AI 数据中心：反对建设的州和社区将被甩在后面",
    "summaryZh": "特朗普当地时间周三在一场聚焦加密货币的活动结束后对记者表示：“我想说，它可能需要在公共关系方面得到一些帮助。 ” 特朗普明确表示，无论公众对数据中心的观感如何，他仍然坚定支持 AI 产业，以及 AI 企业为训练未来模型、满足预期市场需求而需要建设的相关设施。",
    "summaryEn": "特朗普当地时间周三在一场聚焦加密货币的活动结束后对记者表示：“我想说，它可能需要在公共关系方面得到一些帮助。 ” 特朗普明确表示，无论公众对数据中心的观感如何，他仍然坚定支持 AI 产业，以及 AI 企业为训练未来模型、满足预期市场需求而需要建设的相关设施。",
    "whyZh": "立讯需要把重点放在整机柜、供电、散热、高速线缆和连接器，而不是只看 GPU 或服务器品牌。",
    "whyEn": "For Luxshare, the focus should be rack integration, power, thermal, high-speed cable, and connector demand rather than only server brands.",
    "relevance": "低",
    "showByDefault": false,
    "lowValueReason": "IT之家文章缺少明确硬信号或命中低价值内容"
  },
  {
    "id": "real_ithome_2026_08_19_beats_360_beats_studio_pro_1_75",
    "title": "苹果 Beats 360 头戴式耳机偷跑：主动降噪最高达 Beats Studio Pro 的 1.75 倍",
    "signalCategory": "产品",
    "industry": "3C 产品",
    "topic": "",
    "companies": [
      "Apple"
    ],
    "importance": "高",
    "sourceId": "ithome",
    "sourceUrl": "https://www.ithome.com/0/991/867.htm",
    "publishedAt": "2026-08-19",
    "summary": "围绕“苹果 Beats 360 头戴式耳机偷跑：主动降噪最高达 Beats Studio Pro 的 1.75 倍”，这条信息已命中行业硬信号，需要结合原文确认其对需求、供给、成本或客户动作的影响。",
    "whyItMatters": "苹果链信号优先看两点：端侧硬件规格是否升级，以及云端 AI 投入是否带来新的服务器和互连需求。",
    "tags": [
      "AI",
      "Smartphone",
      "Apple"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "zh",
    "sourceWeight": 3,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Technology shift",
      "Customer move",
      "Luxshare business fit"
    ],
    "impactScore": 31,
    "titleZh": "苹果 Beats 360 头戴式耳机偷跑：主动降噪最高达 Beats Studio Pro 的 1.75 倍",
    "titleEn": "苹果 Beats 360 头戴式耳机偷跑：主动降噪最高达 Beats Studio Pro 的 1.75 倍",
    "summaryZh": "围绕“苹果 Beats 360 头戴式耳机偷跑：主动降噪最高达 Beats Studio Pro 的 1.75 倍”，这条信息已命中行业硬信号，需要结合原文确认其对需求、供给、成本或客户动作的影响。",
    "summaryEn": "围绕“苹果 Beats 360 头戴式耳机偷跑：主动降噪最高达 Beats Studio Pro 的 1.75 倍”，这条信息已命中行业硬信号，需要结合原文确认其对需求、供给、成本或客户动作的影响。",
    "whyZh": "苹果链信号优先看两点：端侧硬件规格是否升级，以及云端 AI 投入是否带来新的服务器和互连需求。",
    "whyEn": "For the Apple chain, the key is whether new device form factors change component specifications, assembly yield, or supplier qualification.",
    "relevance": "中",
    "showByDefault": false,
    "lowValueReason": "高相关判断仅依赖泛公司/技术词"
  },
  {
    "id": "real_ithome_2026_08_19_meta_meta_ai_mac",
    "title": "Meta 推出 Meta AI 原生 Mac 应用：支持窗口共享、跨应用听写",
    "signalCategory": "产品",
    "industry": "3C 产品",
    "topic": "",
    "companies": [
      "Apple",
      "Google",
      "Meta"
    ],
    "importance": "高",
    "sourceId": "ithome",
    "sourceUrl": "https://www.ithome.com/0/991/866.htm",
    "publishedAt": "2026-08-19",
    "summary": "这款应用主要面向企业和内容创作者，并与 Facebook 和 Instagram 集成。 应用内置分析工具，可以回答有关账号表现的问题，同时还支持连接 Google Workspace，以访问相关文档。",
    "whyItMatters": "苹果链信号优先看两点：端侧硬件规格是否升级，以及云端 AI 投入是否带来新的服务器和互连需求。",
    "tags": [
      "AI",
      "Apple",
      "Google"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "zh",
    "sourceWeight": 3,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Customer move"
    ],
    "impactScore": 20,
    "titleZh": "Meta 推出 Meta AI 原生 Mac 应用：支持窗口共享、跨应用听写",
    "titleEn": "Meta 推出 Meta AI 原生 Mac 应用：支持窗口共享、跨应用听写",
    "summaryZh": "这款应用主要面向企业和内容创作者，并与 Facebook 和 Instagram 集成。 应用内置分析工具，可以回答有关账号表现的问题，同时还支持连接 Google Workspace，以访问相关文档。",
    "summaryEn": "这款应用主要面向企业和内容创作者，并与 Facebook 和 Instagram 集成。 应用内置分析工具，可以回答有关账号表现的问题，同时还支持连接 Google Workspace，以访问相关文档。",
    "whyZh": "苹果链信号优先看两点：端侧硬件规格是否升级，以及云端 AI 投入是否带来新的服务器和互连需求。",
    "whyEn": "For the Apple chain, the key is whether new device form factors change component specifications, assembly yield, or supplier qualification.",
    "relevance": "中",
    "showByDefault": false,
    "lowValueReason": "IT之家文章缺少明确硬信号或命中低价值内容"
  },
  {
    "id": "real_ithome_2026_08_19_oled_2_0_8_26",
    "title": "天马高端 OLED 天工屏 2.0 发布会定档 8 月 26 日",
    "signalCategory": "产品",
    "industry": "3C 产品",
    "topic": "",
    "companies": [
      "IT之家"
    ],
    "importance": "高",
    "sourceId": "ithome",
    "sourceUrl": "https://www.ithome.com/0/991/852.htm",
    "publishedAt": "2026-08-19",
    "summary": "围绕“天马高端 OLED 天工屏 2.0 发布会定档 8 月 26 日”，这条信息已命中行业硬信号，需要结合原文确认其对需求、供给、成本或客户动作的影响。",
    "whyItMatters": "产品信号只有在带来规格升级、备货变化或供应商切换时，才应进入管理层优先阅读。",
    "tags": [
      "IT之家"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "zh",
    "sourceWeight": 3,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Demand signal"
    ],
    "impactScore": 27,
    "titleZh": "天马高端 OLED 天工屏 2.0 发布会定档 8 月 26 日",
    "titleEn": "天马高端 OLED 天工屏 2.0 发布会定档 8 月 26 日",
    "summaryZh": "围绕“天马高端 OLED 天工屏 2.0 发布会定档 8 月 26 日”，这条信息已命中行业硬信号，需要结合原文确认其对需求、供给、成本或客户动作的影响。",
    "summaryEn": "围绕“天马高端 OLED 天工屏 2.0 发布会定档 8 月 26 日”，这条信息已命中行业硬信号，需要结合原文确认其对需求、供给、成本或客户动作的影响。",
    "whyZh": "产品信号只有在带来规格升级、备货变化或供应商切换时，才应进入管理层优先阅读。",
    "whyEn": "For the Apple chain, the key is whether new device form factors change component specifications, assembly yield, or supplier qualification.",
    "relevance": "高",
    "showByDefault": true
  },
  {
    "id": "real_ithome_2026_08_19_wh_1000xm4c_nfc_qn1_40mm",
    "title": "索尼平价降噪耳机 WH-1000XM4C 更多信息曝光：砍掉 NFC、续航略降，保留 QN1 芯片与 40mm 动圈单元",
    "signalCategory": "产品",
    "industry": "3C 产品",
    "topic": "",
    "companies": [
      "IT之家"
    ],
    "importance": "低",
    "sourceId": "ithome",
    "sourceUrl": "https://www.ithome.com/0/991/851.htm",
    "publishedAt": "2026-08-19",
    "summary": "作为经典 WH-1000XM4 的衍生版本，这款产品在延续原有外观设计的同时，将蓝牙协议升级至 6.0 版本，同时续航表现略有下滑，预计以更低的价格进入市场。",
    "whyItMatters": "产品信号只有在带来规格升级、备货变化或供应商切换时，才应进入管理层优先阅读。",
    "tags": [
      "IT之家"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "zh",
    "sourceWeight": 3,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Cost signal"
    ],
    "impactScore": 0,
    "titleZh": "索尼平价降噪耳机 WH-1000XM4C 更多信息曝光：砍掉 NFC、续航略降，保留 QN1 芯片与 40mm 动圈单元",
    "titleEn": "索尼平价降噪耳机 WH-1000XM4C 更多信息曝光：砍掉 NFC、续航略降，保留 QN1 芯片与 40mm 动圈单元",
    "summaryZh": "作为经典 WH-1000XM4 的衍生版本，这款产品在延续原有外观设计的同时，将蓝牙协议升级至 6.0 版本，同时续航表现略有下滑，预计以更低的价格进入市场。",
    "summaryEn": "作为经典 WH-1000XM4 的衍生版本，这款产品在延续原有外观设计的同时，将蓝牙协议升级至 6.0 版本，同时续航表现略有下滑，预计以更低的价格进入市场。",
    "whyZh": "产品信号只有在带来规格升级、备货变化或供应商切换时，才应进入管理层优先阅读。",
    "whyEn": "For Luxshare, track this only if it changes orders, specifications, qualification paths, customer allocation, or supply risk.",
    "relevance": "低",
    "showByDefault": false,
    "lowValueReason": "IT之家文章缺少明确硬信号或命中低价值内容"
  },
  {
    "id": "real_ithome_2026_08_19_marvell_206_58_10",
    "title": "Marvell 与谷歌签署定制芯片协议并授予其大额认股权证：行权价 206.58 美元，盘前涨超 10%",
    "signalCategory": "产品",
    "industry": "3C 产品",
    "topic": "",
    "companies": [
      "Marvell"
    ],
    "importance": "高",
    "sourceId": "ithome",
    "sourceUrl": "https://www.ithome.com/0/991/834.htm",
    "publishedAt": "2026-08-19",
    "summary": "作为合作的一部分，Marvell 已向谷歌发行了一份认股权证，允许谷歌以每股 206.58 美元（约为昨日收盘价的 95.63%）的行权价格购买至多 5897 万股公司普通股。",
    "whyItMatters": "产品信号只有在带来规格升级、备货变化或供应商切换时，才应进入管理层优先阅读。",
    "tags": [
      "AI",
      "Marvell"
    ],
    "dataSourceType": "真实采集",
    "originalLanguage": "zh",
    "sourceWeight": 3,
    "sourceCategory": "discovery",
    "briefingValue": [
      "Demand signal",
      "Cost signal",
      "Customer move"
    ],
    "impactScore": 38,
    "titleZh": "Marvell 与谷歌签署定制芯片协议并授予其大额认股权证：行权价 206.58 美元，盘前涨超 10%",
    "titleEn": "Marvell 与谷歌签署定制芯片协议并授予其大额认股权证：行权价 206.58 美元，盘前涨超 10%",
    "summaryZh": "作为合作的一部分，Marvell 已向谷歌发行了一份认股权证，允许谷歌以每股 206.58 美元（约为昨日收盘价的 95.63%）的行权价格购买至多 5897 万股公司普通股。",
    "summaryEn": "作为合作的一部分，Marvell 已向谷歌发行了一份认股权证，允许谷歌以每股 206.58 美元（约为昨日收盘价的 95.63%）的行权价格购买至多 5897 万股公司普通股。",
    "whyZh": "产品信号只有在带来规格升级、备货变化或供应商切换时，才应进入管理层优先阅读。",
    "whyEn": "For Luxshare, track this only if it changes orders, specifications, qualification paths, customer allocation, or supply risk.",
    "relevance": "中",
    "showByDefault": false,
    "lowValueReason": "IT之家文章缺少明确硬信号或命中低价值内容"
  }
];
