const radarSources = [
  {
    id: "nvidia_newsroom",
    name: "NVIDIA Newsroom",
    url: "https://nvidianews.nvidia.com/",
    type: "official_news",
    fetchType: "rss_or_html",
    industries: ["数据中心硬件", "核心零部件"],
    signalCategories: ["供应链", "产品", "公司动态"],
    priority: 1,
    active: true
  },
  {
    id: "eetimes",
    name: "EE Times",
    url: "https://www.eetimes.com/",
    type: "editorial_media",
    fetchType: "rss",
    industries: ["核心零部件", "3C 产品"],
    signalCategories: ["供应链", "产品", "公司动态"],
    priority: 1,
    active: true
  },
  {
    id: "semiconductor_engineering",
    name: "Semiconductor Engineering",
    url: "https://semiengineering.com/",
    type: "editorial_media",
    fetchType: "rss",
    industries: ["核心零部件"],
    signalCategories: ["供应链", "产品"],
    priority: 1,
    active: true
  },
  {
    id: "trendforce_news",
    name: "TrendForce News",
    url: "https://www.trendforce.com/news/",
    type: "research_news",
    fetchType: "rss",
    industries: ["核心零部件", "3C 产品", "数据中心硬件"],
    signalCategories: ["供应链", "产品"],
    priority: 1,
    active: true
  },
  {
    id: "tomshardware",
    name: "Tom's Hardware",
    url: "https://www.tomshardware.com/",
    type: "editorial_media",
    fetchType: "rss_filtered",
    industries: ["核心零部件", "3C 产品"],
    signalCategories: ["产品", "供应链"],
    priority: 2,
    active: true
  },
  {
    id: "techpowerup",
    name: "TechPowerUp",
    url: "https://www.techpowerup.com/",
    type: "editorial_media",
    fetchType: "rss_filtered",
    industries: ["核心零部件", "3C 产品"],
    signalCategories: ["产品", "供应链"],
    priority: 2,
    active: true
  },
  {
    id: "servethehome",
    name: "ServeTheHome",
    url: "https://www.servethehome.com/",
    type: "editorial_media",
    fetchType: "rss",
    industries: ["数据中心硬件"],
    signalCategories: ["供应链", "产品"],
    priority: 1,
    active: true
  },
  {
    id: "storagereview",
    name: "StorageReview",
    url: "https://www.storagereview.com/",
    type: "editorial_media",
    fetchType: "rss_filtered",
    industries: ["数据中心硬件"],
    signalCategories: ["供应链", "产品"],
    priority: 1,
    active: true
  },
  {
    id: "apple_newsroom",
    name: "Apple Newsroom",
    url: "https://www.apple.com/newsroom/",
    type: "official_news",
    fetchType: "rss_or_html",
    industries: ["3C 产品"],
    signalCategories: ["产品", "供应链", "公司动态"],
    priority: 1,
    active: true
  },
  {
    id: "intel_newsroom",
    name: "Intel Newsroom",
    url: "https://www.intel.com/content/www/us/en/newsroom/home.html",
    type: "official_news",
    fetchType: "rss_or_html",
    industries: ["核心零部件", "数据中心硬件"],
    signalCategories: ["产品", "公司动态", "供应链"],
    priority: 1,
    active: true
  },
  {
    id: "amd_newsroom",
    name: "AMD Newsroom",
    url: "https://www.amd.com/en/newsroom.html",
    type: "official_news",
    fetchType: "rss_or_html",
    industries: ["核心零部件", "数据中心硬件"],
    signalCategories: ["产品", "公司动态"],
    priority: 1,
    active: true
  },
  {
    id: "qualcomm_news",
    name: "Qualcomm News",
    url: "https://www.qualcomm.com/news",
    type: "official_news",
    fetchType: "rss_or_html",
    industries: ["3C 产品", "核心零部件"],
    signalCategories: ["产品", "公司动态"],
    priority: 1,
    active: true
  },
  {
    id: "mediatek_press",
    name: "MediaTek Press Releases",
    url: "https://www.mediatek.com/news-events/press-releases",
    type: "official_news",
    fetchType: "html",
    industries: ["3C 产品", "核心零部件"],
    signalCategories: ["产品", "公司动态"],
    priority: 2,
    active: true
  },
  {
    id: "samsung_newsroom",
    name: "Samsung Newsroom",
    url: "https://news.samsung.com/global/",
    type: "official_news",
    fetchType: "rss_or_html",
    industries: ["3C 产品", "核心零部件"],
    signalCategories: ["产品", "供应链", "公司动态"],
    priority: 2,
    active: true
  },
  {
    id: "micron_blog",
    name: "Micron Blog",
    url: "https://www.micron.com/about/blog",
    type: "official_news",
    fetchType: "html",
    industries: ["核心零部件", "数据中心硬件"],
    signalCategories: ["供应链", "产品", "财报"],
    priority: 2,
    active: true
  },
  {
    id: "marvell_newsroom",
    name: "Marvell Newsroom",
    url: "https://www.marvell.com/company/newsroom.html",
    type: "official_news",
    fetchType: "html",
    industries: ["数据中心硬件", "核心零部件"],
    signalCategories: ["产品", "公司动态"],
    priority: 2,
    active: true
  },
  {
    id: "vertiv_news",
    name: "Vertiv News & Insights",
    url: "https://www.vertiv.com/en-us/about/news-and-insights/",
    type: "official_news",
    fetchType: "html",
    industries: ["数据中心硬件"],
    signalCategories: ["供应链", "产品", "公司动态"],
    priority: 2,
    active: true
  },
  {
    id: "foxconn_press",
    name: "Foxconn Press Releases",
    url: "https://www.foxconn.com/en-us/press-center/press-releases",
    type: "official_news",
    fetchType: "html",
    industries: ["3C 产品", "数据中心硬件"],
    signalCategories: ["供应链", "公司动态", "财报"],
    priority: 2,
    active: true
  },
  {
    id: "microsoft_ir",
    name: "Microsoft Investor Relations",
    url: "https://www.microsoft.com/en-us/investor",
    type: "investor_relations",
    fetchType: "html",
    industries: ["数据中心硬件", "财报/产业信号"],
    signalCategories: ["财报", "宏观经济"],
    priority: 1,
    active: true
  },
  {
    id: "amazon_ir",
    name: "Amazon Investor Relations",
    url: "https://ir.aboutamazon.com/",
    type: "investor_relations",
    fetchType: "html",
    industries: ["数据中心硬件", "财报/产业信号"],
    signalCategories: ["财报"],
    priority: 1,
    active: true
  },
  {
    id: "sec_edgar",
    name: "SEC EDGAR",
    url: "https://www.sec.gov/edgar/search/",
    type: "filings",
    fetchType: "api",
    industries: ["3C 产品", "数据中心硬件", "财报/产业信号"],
    signalCategories: ["财报", "公司动态", "宏观经济"],
    priority: 1,
    active: true
  },
  {
    id: "sony_press",
    name: "Sony Press Releases",
    url: "https://www.sony.com/en/SonyInfo/News/Press/",
    type: "official_news",
    fetchType: "html",
    industries: ["3C 产品", "核心零部件"],
    signalCategories: ["产品", "供应链"],
    priority: 3,
    active: true
  },
  {
    id: "meta_news",
    name: "Meta Newsroom",
    url: "https://about.meta.com/news/",
    type: "official_news",
    fetchType: "html",
    industries: ["3C 产品", "数据中心硬件"],
    signalCategories: ["产品", "公司动态", "财报"],
    priority: 3,
    active: true
  },
  {
    id: "federal_reserve",
    name: "Federal Reserve News",
    url: "https://www.federalreserve.gov/newsevents.htm",
    type: "macro",
    fetchType: "html",
    industries: ["财报/产业信号"],
    signalCategories: ["宏观经济"],
    priority: 3,
    active: true
  },
  {
    id: "industry_research_placeholder",
    name: "Industry Research Queue",
    url: "",
    type: "research_queue",
    fetchType: "manual",
    industries: ["3C 产品", "核心零部件", "数据中心硬件"],
    signalCategories: ["供应链", "产品", "财报"],
    priority: 3,
    active: false
  },
  {
    id: "blocks_and_files",
    name: "Blocks & Files",
    url: "https://blocksandfiles.com/",
    type: "editorial_media",
    fetchType: "candidate_html_or_feed",
    industries: ["数据中心硬件"],
    signalCategories: ["供应链", "产品"],
    priority: 1,
    active: false
  },
  {
    id: "the_register",
    name: "The Register",
    url: "https://www.theregister.com/",
    type: "editorial_media",
    fetchType: "candidate_atom",
    industries: ["数据中心硬件", "核心零部件"],
    signalCategories: ["供应链", "产品", "公司动态"],
    priority: 1,
    active: false
  },
  {
    id: "open_compute_project",
    name: "Open Compute Project",
    url: "https://www.opencompute.org/blog",
    type: "official_blog",
    fetchType: "candidate_html",
    industries: ["数据中心硬件"],
    signalCategories: ["供应链", "产品"],
    priority: 1,
    active: false
  },
  {
    id: "data_center_dynamics",
    name: "Data Center Dynamics",
    url: "https://www.datacenterdynamics.com/",
    type: "editorial_media",
    fetchType: "candidate_html",
    industries: ["数据中心硬件"],
    signalCategories: ["供应链", "产品"],
    priority: 2,
    active: false
  },
  {
    id: "light_reading",
    name: "Light Reading",
    url: "https://www.lightreading.com/",
    type: "editorial_media",
    fetchType: "candidate_filtered",
    industries: ["数据中心硬件"],
    signalCategories: ["供应链"],
    priority: 2,
    active: false
  }
];
